import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

await import('../src/pages/career/career-match-football-flow-patch.js?v=20260811-2');
await import('../src/pages/career/career-match-balance-v3.js?v=20260812-1');
await import('../src/pages/career/career-match-action-balance-v4.js?v=20260813-1');
const { normalizeCareerChoice }=await import('../src/pages/career/career-match-possession-chain-v5.js?v=20260813-1');
const { careerDecisionSemantic,consequenceModeFor,hasCoherentConsequencePolicy,applyCareerConsequenceFeedback,triggerStoredCounterIfReady }=await import('../src/pages/career/career-match-consequence-coherence-v7.js?v=20260813-1');
await import('../src/pages/career/career-match-decision-option-guard.js?v=20260813-1');
await import('../src/pages/career/career-match-gameplay-depth-v2.js?v=20260812-2');
const { CareerMatchEngine }=await import('../src/pages/career/career-match-engine-v2.js?v=20260811-1');

const positions=['GOL','LD','ZAG','ZAG','LE','VOL','MC','MEI','PD','ATA','PE'];
function roster(prefix,base=58){return positions.map((position,index)=>{const d=['LD','LE','ZAG','VOL'].includes(position),c=['MC','MEI'].includes(position),a=['PD','PE','ATA'].includes(position),ovr=base+(c?2:a?1:0);return{id:`${prefix}-${index}`,name:`${prefix} ${index}`,position,ovr,probable_starter:true,chemistry:62,attributes:{Velocidade:ovr+(a?5:0),Passe:ovr+(c?6:0),'Finalização':ovr+(a?5:-5),'Físico':ovr+(d?5:0),'Visão de jogo':ovr+(c?7:0),'Marcação':ovr+(d?8:-8)}};});}
function context(seed='coherence'){return{seed,matchDate:'2026-10-10',player:{id:'user',name:'Oliver',nickname:'Oliver',position:'ATA',ovr:58,attributes:{Velocidade:63,Passe:55,'Finalização':57,'Físico':50,'Visão de jogo':58,'Marcação':34},skills:{dribbling:57,positioning:60,stamina:52,short_pass:56,long_pass:54,crossing:53,heading:55,tactical_awareness:57}},state:{energy:94,fatigue:8,readiness:84},selection:{status:'starter'},performance:{preparation_score:84,mental_stability:78},club:{name:'União Litorânea Sub-17',formation:'4-3-3',play_style:'equilibrado'},home:{name:'União Litorânea Sub-17',formation:'4-3-3',players:roster('Casa',60)},away:{name:'Rival Sub-17',formation:'4-3-3',players:roster('Fora',58)}};}
function engineFor(seed){const e=new CareerMatchEngine(context(seed));e.start();e.user.energy=92;return e;}
function mate(e){return e.home.find(p=>p.onField&&!p.isUser&&p.role!=='gk');}
function rival(e){return e.away.find(p=>p.onField&&p.role!=='gk');}
function setBall(e,p){e.possession=p.team;e.ball.ownerId=p.id;e.ball.x=p.x;e.ball.y=p.y;}
function prepare(e,choice,{situation='central_ball',progress=65,owner=e.user}={}){e.user.x=progress;e.user.y=50;setBall(e,owner);const c=normalizeCareerChoice({energyCost:choice.cost??2,context:{pressure:18,space:82,markers:0,progress,angle:88},...choice,difficulty:choice.difficulty??1});e.pendingDecision={situation:{key:situation,title:'Teste'},options:[c],chain:0};e.awaitingDecision=true;e.paused=true;return c;}
const flush=()=>new Promise(resolve=>queueMicrotask(resolve));
const progress=(e,p)=>e.homeAttacksRight?p.x:100-p.x;

test('every gameplay option has a consequence policy',()=>{const source=fs.readFileSync(new URL('../src/pages/career/career-match-gameplay-depth-v2.js',import.meta.url),'utf8'),row=/\['([^']+)','[^']*','[^']+',-?\d+,\d+,\[([^\]]*)\]/g;let count=0,m;while((m=row.exec(source))){const key=m[1],tags=[...m[2].matchAll(/'([^']+)'/g)].map(x=>x[1]);count++;assert.notEqual(careerDecisionSemantic({key,tags}),'other',key);assert.ok(hasCoherentConsequencePolicy({key,tags}),key);assert.ok(['terminal','immediate_or_terminal','persistent_or_contextual'].includes(consequenceModeFor({key,tags})));}assert.ok(count>=55,`parsed ${count}`);});

test('counter outlet waits for a real recovery, then becomes playable',async()=>{const e=engineFor('outlet'),opp=rival(e);e.matchFlow.phase='counter';e.matchFlow.transitionUntil=e.minute+2;const c=prepare(e,{key:'rec_high',label:'Ficar alto para o contra-ataque',skill:'positioning',cost:1,tags:['risk']},{situation:'recovery_choice',progress:58,owner:opp}),ownerBefore=e.ball.ownerId,r=e.choose('rec_high');await flush();assert.ok(r.success);assert.equal(e.possession,'away');assert.equal(e.ball.ownerId,ownerBefore);assert.ok(e.__coherentCounterOutlet);const detail={engine:e,result:r,choice:c,continued:false};applyCareerConsequenceFeedback(detail);assert.match(r.outcomeText,/ainda tem a bola/i);assert.equal(detail.continued,false);const before='away';setBall(e,mate(e));e.matchFlow.phase='counter';e.matchFlow.transitionUntil=e.minute+2;assert.equal(triggerStoredCounterIfReady(e,before),true);assert.equal(e.pendingDecision?.situation?.key,'off_ball_attack');assert.ok(e.pendingDecision?.options?.length>=3);});

test('containment reduces danger without magically recovering the ball',async()=>{const e=engineFor('contain'),opp=rival(e);e.matchFlow.phase='counter';e.matchFlow.transitionUntil=e.minute+2;const c=prepare(e,{key:'rec_center',label:'Fechar o corredor central',skill:'tactical',cost:5,tags:['defend','run']},{situation:'recovery_choice',owner:opp}),ownerBefore=e.ball.ownerId,r=e.choose('rec_center');await flush();assert.ok(r.success);assert.equal(e.possession,'away');assert.equal(e.ball.ownerId,ownerBefore);assert.notEqual(e.matchFlow.phase,'counter');const detail={engine:e,result:r,choice:c,continued:false};applyCareerConsequenceFeedback(detail);assert.match(r.outcomeText,/obrigou o rival/i);});

test('shield keeps the ball and materializes the arriving support',async()=>{const e=engineFor('shield'),c=prepare(e,{key:'build_shield',label:'Proteger a bola e esperar apoio',skill:'strength',cost:4,tags:['duel','support']},{situation:'build_under_pressure',progress:34}),r=e.choose('build_shield');await flush();assert.ok(r.success);assert.equal(e.ball.ownerId,e.user.id);const detail={engine:e,result:r,choice:c,continued:false};applyCareerConsequenceFeedback(detail);assert.equal(detail.continued,true);assert.ok(e.pendingDecision?.options?.length>=3);});

test('recycle pass really sends possession backward',async()=>{const e=engineFor('recycle'),c=prepare(e,{key:'central_hold',label:'Cadenciar e tocar para trás',skill:'shortPass',cost:1,tags:['pass','support']},{progress:75}),r=e.choose('central_hold');await flush();assert.ok(r.success);const receiver=e.home.find(p=>p.id===e.ball.ownerId);assert.ok(receiver&&!receiver.isUser);assert.ok(progress(e,receiver)<75);});

test('switch pass actually changes corridor',async()=>{const e=engineFor('switch');e.user.y=16;const c=prepare(e,{key:'central_switch',label:'Inverter para o lado oposto',skill:'longPass',cost:4,tags:['pass']},{progress:62});e.user.y=16;e.ball.y=16;const r=e.choose('central_switch');await flush();assert.ok(r.success);const receiver=e.home.find(p=>p.id===e.ball.ownerId);assert.ok(receiver&&!receiver.isUser);assert.ok(Math.abs(receiver.y-16)>=25,`receiver y=${receiver.y}`);});

test('intercept-and-launch is an interception, not a fake pass, and creates a counter',async()=>{const e=engineFor('launch'),opp=rival(e),passes=e.playerStats.passesAttempted,c=prepare(e,{key:'sp_intercept_launch',label:'Antecipar e lançar o contra-ataque',skill:'tactical',cost:7,tags:['interception','chance','special']},{situation:'recovery_choice',progress:49,owner:opp}),r=e.choose('sp_intercept_launch');await flush();assert.ok(r.success);assert.equal(e.playerStats.passesAttempted,passes);assert.equal(e.possession,'home');assert.equal(e.matchFlow.phase,'counter');const detail={engine:e,result:r,choice:c,continued:false};applyCareerConsequenceFeedback(detail);assert.equal(detail.continued,true);assert.equal(e.pendingDecision?.situation?.key,'off_ball_attack');});