BEGIN;

INSERT INTO private.career_event_templates(event_key,source,title,body,choices) VALUES
('mate_training_tip','Companheiro','Um detalhe no seu movimento','Depois do treino, um companheiro comenta que percebeu um detalhe na forma como você recebe a bola e oferece uma sugestão.',
 '[{"key":"listen","label":"Ouvir e pedir para ele mostrar na prática.","effects":{"locker":2,"teammate_relation":5,"professionalism":1,"skills":{"tactical_awareness":2}},"result":"Você transformou o comentário em aprendizado.","reply_speaker":"Companheiro","reply":"Boa. Amanhã eu te mostro no campo. É coisa pequena, mas abre espaço quando você acerta o tempo."},{"key":"thank","label":"Agradecer, mas dizer que prefere trabalhar do seu jeito.","effects":{"teammate_relation":1,"morale":1,"ego":1},"result":"Você foi cordial sem mudar sua rotina.","reply_speaker":"Companheiro","reply":"Tranquilo. Cada um sente o jogo de um jeito. Só achei que podia ajudar."},{"key":"dismiss","label":"Dizer que não acha que isso seja um problema.","effects":{"teammate_relation":-3,"ego":2},"result":"O assunto morreu rápido e ficou um pequeno incômodo.","reply_speaker":"Companheiro","reply":"Beleza. Esquece então. Eu só estava tentando somar."}]'::jsonb),
('mate_extra_session_invite','Companheiro','Treino depois do treino','Um companheiro pergunta se você topa ficar mais alguns minutos depois da atividade para repetir jogadas específicas.',
 '[{"key":"join","label":"Aceitar e combinar uma sessão curta juntos.","effects":{"locker":2,"teammate_relation":6,"energy":-2,"fatigue":1,"skills":{"short_pass":2}},"result":"Vocês criaram uma pequena rotina de trabalho extra.","reply_speaker":"Companheiro","reply":"Fechado. Nada de exagerar. Uns minutos bem feitos valem mais do que ficar aqui até quebrar."},{"key":"later","label":"Dizer que hoje precisa recuperar, mas deixar para outro dia.","effects":{"teammate_relation":2,"discipline":1,"energy":1},"result":"Você preservou o corpo sem fechar a porta.","reply_speaker":"Companheiro","reply":"Justo. Me chama quando estiver inteiro e a gente faz."},{"key":"decline","label":"Recusar sem se comprometer com outra sessão.","effects":{"teammate_relation":-2,"personal":1},"result":"Ele entendeu, mas não insistiu mais.","reply_speaker":"Companheiro","reply":"Sem problema. Eu vou ficar um pouco mesmo assim."}]'::jsonb),
('mate_pass_complaint','Companheiro','“Eu estava livre.”','No fim da atividade, um companheiro comenta que você ignorou algumas opções de passe em jogadas em que ele aparecia livre.',
 '[{"key":"own","label":"Admitir que poderia ter levantado a cabeça mais cedo.","effects":{"locker":2,"teammate_relation":5,"ego":-1,"skills":{"tactical_awareness":2}},"result":"A conversa terminou com entendimento.","reply_speaker":"Companheiro","reply":"É só isso. Se eu estiver livre, confia. Eu também vou procurar você quando tiver espaço."},{"key":"explain","label":"Explicar o que você enxergou nas jogadas.","effects":{"teammate_relation":2,"professionalism":1},"result":"Vocês compararam leituras diferentes da mesma jogada.","reply_speaker":"Companheiro","reply":"Entendi seu lado. Então vamos ajustar o movimento para você ter as duas opções."},{"key":"pushback","label":"Responder que a decisão com a bola é sua.","effects":{"locker":-2,"teammate_relation":-6,"ego":3,"rivalry":1},"result":"O tom deixou a relação mais competitiva.","reply_speaker":"Companheiro","reply":"Beleza. Mas depois não reclama quando eu também escolher resolver sozinho."}]'::jsonb),
('mate_support_bad_week','Companheiro','Um apoio inesperado','Um jogador percebe que sua semana está pesada e pergunta se está tudo bem fora do campo.',
 '[{"key":"open","label":"Falar um pouco sobre a pressão que está sentindo.","effects":{"pressure":-4,"morale":3,"teammate_relation":6,"locker":2},"result":"A conversa tirou um pouco do peso da semana.","reply_speaker":"Companheiro","reply":"Todo mundo aqui passa por isso. Se precisar conversar, não precisa guardar tudo sozinho."},{"key":"light","label":"Dizer que está tudo sob controle e agradecer.","effects":{"pressure":-1,"teammate_relation":3},"result":"Você manteve a conversa leve.","reply_speaker":"Companheiro","reply":"Então beleza. Só quis ter certeza. Vamos nessa."},{"key":"close","label":"Evitar o assunto e dizer que prefere ficar sozinho.","effects":{"personal":2,"teammate_relation":-2,"locker":-1},"result":"Você preservou seu espaço, mas criou alguma distância.","reply_speaker":"Companheiro","reply":"Tranquilo. Respeito. Se mudar de ideia, sabe onde me achar."}]'::jsonb),
('mate_media_jealousy','Companheiro','Seu nome está aparecendo bastante','Um companheiro brinca que a imprensa parece interessada em tudo o que você faz e pergunta se você está gostando da atenção.',
 '[{"key":"team","label":"Dizer que prefere que falem do time, não só de você.","effects":{"locker":3,"teammate_relation":4,"ego":-2,"image":1},"result":"A resposta agradou quem teme que a exposição suba à cabeça.","reply_speaker":"Companheiro","reply":"Boa. Aqui ninguém ganha jogo sozinho. Se continuar assim, a galera vai comprar sua ideia."},{"key":"enjoy","label":"Admitir que gosta da exposição e quer aproveitar o momento.","effects":{"fame":1,"media":2,"teammate_relation":-1,"ego":2},"result":"Você não escondeu que gosta dos holofotes.","reply_speaker":"Companheiro","reply":"Justo. Só lembra que quando sobe rápido, a cobrança sobe junto."},{"key":"joke","label":"Brincar que ele está com ciúme das entrevistas.","effects":{"sociability":2,"teammate_relation":1,"locker":1},"result":"O clima virou piada.","reply_speaker":"Companheiro","reply":"Ciúme nada. Só quero meu microfone também quando eu fizer dois gols."}]'::jsonb),
('mate_social_invite','Companheiro','Convite depois do treino','Um companheiro chama você para sair com parte do elenco depois do expediente.',
 '[{"key":"go","label":"Aceitar o convite e combinar de ir com o grupo.","effects":{"locker":4,"teammate_relation":5,"morale":3,"energy":-2,"personal":2},"result":"Você se aproximou do grupo fora do ambiente de treino.","reply_speaker":"Companheiro","reply":"Boa. Sem loucura, só para relaxar um pouco. Vai ser bom você conhecer a galera fora daqui."},{"key":"short","label":"Dizer que aparece um pouco, mas vai embora cedo.","effects":{"locker":2,"teammate_relation":3,"discipline":1},"result":"Você conciliou integração e rotina.","reply_speaker":"Companheiro","reply":"Fechado. O importante é aparecer. Depois cada um cuida do próprio horário."},{"key":"no","label":"Recusar porque quer priorizar recuperação.","effects":{"discipline":2,"energy":2,"teammate_relation":-1},"result":"Você priorizou sua preparação.","reply_speaker":"Companheiro","reply":"Tá focado mesmo, hein? Tranquilo. Outra hora você cola."}]'::jsonb),
('mate_prank','Companheiro','Pegadinha no vestiário','Um companheiro tenta te colocar numa brincadeira do grupo para ver como você reage.',
 '[{"key":"play","label":"Entrar na brincadeira e devolver na mesma moeda.","effects":{"locker":4,"teammate_relation":4,"sociability":3,"morale":2},"result":"Você entrou no clima do grupo.","reply_speaker":"Companheiro","reply":"Agora sim. Achei que você ia ficar sério o tempo todo."},{"key":"smile","label":"Levar na esportiva, mas não prolongar.","effects":{"locker":2,"teammate_relation":2,"sociability":1},"result":"Você mostrou que sabe brincar sem perder o limite.","reply_speaker":"Companheiro","reply":"Tá bom, tá bom. Você passou no teste do vestiário."},{"key":"angry","label":"Cortar a brincadeira e dizer que não gostou.","effects":{"locker":-3,"teammate_relation":-4,"discipline":1},"result":"O clima esfriou imediatamente.","reply_speaker":"Companheiro","reply":"Calma. Era só brincadeira. Já entendi que com você não rola."}]'::jsonb),
('mate_tactical_disagreement','Companheiro','Leituras diferentes','Durante uma conversa tática, um companheiro discorda de onde você deveria se posicionar numa jogada recorrente.',
 '[{"key":"test","label":"Propor testar as duas ideias no próximo treino.","effects":{"locker":2,"teammate_relation":4,"professionalism":2,"skills":{"positioning":2}},"result":"A divergência virou experimento em campo.","reply_speaker":"Companheiro","reply":"Fechado. Se a sua funcionar melhor, eu admito. Se a minha funcionar, você me paga um café."},{"key":"coach","label":"Dizer que prefere seguir exatamente o que o treinador pediu.","effects":{"coach":2,"discipline":2,"teammate_relation":-1},"result":"Você priorizou a orientação da comissão.","reply_speaker":"Companheiro","reply":"Justo. Depois eu pergunto para ele como quer essa movimentação."},{"key":"insist","label":"Insistir que sua leitura é claramente melhor.","effects":{"teammate_relation":-5,"ego":2,"locker":-1},"result":"A discussão ficou mais pessoal do que tática.","reply_speaker":"Companheiro","reply":"Então mostra no treino. Falar que é melhor é fácil."}]'::jsonb),
('mate_penalty_talker','Companheiro','Quem bate se acontecer?','Um companheiro pergunta quem deveria assumir um pênalti importante se os dois estiverem em campo.',
 '[{"key":"claim","label":"Dizer que quer a responsabilidade se estiver confiante.","effects":{"ambition":2,"teammate_relation":-2,"pressure":2,"skills":{"penalties":1}},"result":"Você deixou claro que quer decisões grandes.","reply_speaker":"Companheiro","reply":"Gostei da coragem. Mas se eu estiver melhor no dia, vou querer também."},{"key":"merit","label":"Dizer que deve bater quem estiver melhor e for definido pela comissão.","effects":{"coach":2,"locker":2,"teammate_relation":3,"ego":-1},"result":"Você colocou a decisão acima da disputa pessoal.","reply_speaker":"Companheiro","reply":"Fechado. Sem ego. Quem estiver mais preparado assume."},{"key":"give","label":"Dizer que ele pode assumir e você prefere não entrar nessa disputa.","effects":{"pressure":-2,"teammate_relation":4,"ambition":-2},"result":"Você tirou uma disputa da mesa.","reply_speaker":"Companheiro","reply":"Valeu pela confiança. Mas se chegar sua hora, não foge dela."}]'::jsonb),
('mate_agent_rumor','Companheiro','“Estão falando que você pode sair.”','Um jogador pergunta diretamente sobre rumores de que seu empresário estaria conversando com outros clubes.',
 '[{"key":"deny","label":"Dizer que seu foco está totalmente no clube atual.","effects":{"locker":3,"teammate_relation":3,"fans":1,"agent":-1},"result":"Você tentou encerrar a especulação dentro do grupo.","reply_speaker":"Companheiro","reply":"Boa. Era só isso que eu queria ouvir. Rumor de fora entra fácil no vestiário."},{"key":"honest","label":"Dizer que escuta oportunidades, mas não decidiu nada.","effects":{"teammate_relation":1,"agent":2,"ambition":1,"locker":-1},"result":"A sinceridade manteve a conversa aberta, mas não matou o rumor.","reply_speaker":"Companheiro","reply":"Entendo. Só não deixa a gente descobrir tudo pela internet."},{"key":"private","label":"Dizer que sua carreira não é assunto do vestiário.","effects":{"teammate_relation":-4,"personal":2,"ego":1},"result":"Você protegeu sua privacidade e criou distância.","reply_speaker":"Companheiro","reply":"Beleza. Não pergunto mais. Só achei que valia falar de frente."}]'::jsonb),
('mate_cover_late','Companheiro','Ele pode te cobrir','Um companheiro percebe que você está atrasado para uma reunião interna e oferece uma desculpa para a comissão.',
 '[{"key":"accept","label":"Aceitar a cobertura e entrar sem chamar atenção.","effects":{"teammate_relation":5,"discipline":-3,"coach":-1},"result":"Você escapou da cobrança imediata, mas dependeu do companheiro.","reply_speaker":"Companheiro","reply":"Eu seguro essa. Mas não me faz virar seu álibi toda semana."},{"key":"own","label":"Recusar e assumir o atraso diretamente.","effects":{"coach":1,"discipline":3,"teammate_relation":2,"pressure":1},"result":"Você preferiu assumir a consequência.","reply_speaker":"Companheiro","reply":"Respeito. Melhor tomar a bronca agora do que criar história depois."},{"key":"blame","label":"Pedir para ele dizer que a comissão mudou o horário.","effects":{"teammate_relation":-5,"discipline":-4,"image":-1},"result":"O pedido deixou o companheiro desconfortável.","reply_speaker":"Companheiro","reply":"Aí não. Uma coisa é te dar cobertura, outra é inventar coisa colocando os outros no meio."}]'::jsonb),
('mate_mentor_advice','Companheiro','Conselho de quem já está aqui','Um dos jogadores mais estabelecidos no elenco chama você de lado e comenta sobre como sobreviver às semanas ruins.',
 '[{"key":"ask","label":"Perguntar o que mais pesa para um jovem dentro do clube.","effects":{"professionalism":2,"teammate_relation":5,"pressure":-2},"result":"Você recebeu um conselho mais profundo do que esperava.","reply_speaker":"Companheiro","reply":"Não é errar. É deixar um erro virar três dias ruins. Aprende a zerar rápido e volta para o próximo treino."},{"key":"confident","label":"Dizer que acredita conseguir lidar sozinho com a pressão.","effects":{"ambition":1,"morale":2,"teammate_relation":-1},"result":"Você demonstrou autoconfiança.","reply_speaker":"Companheiro","reply":"Tomara. Só não confunde confiança com achar que ninguém tem nada para ensinar."},{"key":"thank","label":"Agradecer e guardar o conselho sem prolongar a conversa.","effects":{"teammate_relation":3,"professionalism":1},"result":"A relação ganhou respeito sem grande exposição.","reply_speaker":"Companheiro","reply":"Tranquilo. Quando precisar, chega aí."}]'::jsonb),
('mate_ask_help','Companheiro','Ele quer sua ajuda','Um companheiro pede alguns minutos para você ajudá-lo a repetir uma situação em que ele está tendo dificuldade.',
 '[{"key":"help","label":"Ficar e ajudá-lo mesmo gastando parte do seu tempo livre.","effects":{"locker":4,"teammate_relation":7,"leadership":2,"energy":-2},"result":"Você investiu tempo na evolução de outro jogador.","reply_speaker":"Companheiro","reply":"Valeu mesmo. Quando você precisar repetir alguma coisa, me chama também."},{"key":"brief","label":"Ajudar rapidamente, mas manter seu plano do dia.","effects":{"locker":2,"teammate_relation":4,"professionalism":1},"result":"Você ajudou sem abandonar sua própria rotina.","reply_speaker":"Companheiro","reply":"Já clareou bastante. O resto eu continuo sozinho."},{"key":"no","label":"Dizer que precisa focar no seu próprio desenvolvimento.","effects":{"ambition":2,"teammate_relation":-3,"locker":-1},"result":"Você priorizou seu desenvolvimento individual.","reply_speaker":"Companheiro","reply":"Beleza. Eu resolvo. Só achei que você podia dar uma força."}]'::jsonb),
('mate_music_room','Companheiro','Quem manda na música?','Um companheiro entrega o celular e manda você escolher a música do vestiário antes do treino.',
 '[{"key":"takeover","label":"Assumir a playlist e colocar o que você gosta.","effects":{"sociability":3,"locker":2,"teammate_relation":2,"ego":1},"result":"Você deixou um pouco mais da sua personalidade no ambiente.","reply_speaker":"Companheiro","reply":"Tá aprovado... por enquanto. Se a gente perder, a culpa da playlist é sua."},{"key":"group","label":"Perguntar o que o grupo quer ouvir e montar junto.","effects":{"locker":4,"teammate_relation":3,"leadership":1},"result":"A escolha virou um pequeno momento coletivo.","reply_speaker":"Companheiro","reply":"Aí sim. Democracia até alguém colocar uma música horrível."},{"key":"pass","label":"Devolver o celular e dizer que não liga para isso.","effects":{"teammate_relation":0,"sociability":-1},"result":"Você ficou fora da brincadeira.","reply_speaker":"Companheiro","reply":"Você é difícil, hein? Então deixa que eu resolvo."}]'::jsonb),
('mate_social_post','Companheiro','Foto do elenco','Um companheiro quer postar uma foto de vocês depois do treino e pergunta se pode marcar seu perfil.',
 '[{"key":"yes","label":"Deixar postar e entrar na brincadeira nos comentários.","effects":{"locker":2,"teammate_relation":3,"media":1,"image":1,"fame":1,"fanbase":8},"result":"A publicação aproximou sua imagem do grupo.","reply_speaker":"Companheiro","reply":"Boa. Já vou postar antes que você mude de ideia."},{"key":"photo_only","label":"Deixar postar, mas pedir para não marcar seu perfil.","effects":{"teammate_relation":1,"personal":2},"result":"Você preservou parte da privacidade sem criar conflito.","reply_speaker":"Companheiro","reply":"Fechado. Foto vai, marcação não."},{"key":"no","label":"Pedir para não publicar a foto.","effects":{"personal":3,"teammate_relation":-2,"locker":-1},"result":"O companheiro respeitou, embora tenha achado estranho.","reply_speaker":"Companheiro","reply":"Tá bom. Eu corto você da foto. Sem problema."}]'::jsonb),
('mate_captain_standard','Capitão','O padrão do grupo','O capitão comenta que algumas atitudes pequenas no dia a dia definem quem o elenco passa a confiar quando a pressão aumenta.',
 '[{"key":"ask","label":"Perguntar o que ele espera de você especificamente.","effects":{"locker":3,"teammate_relation":4,"leadership":1,"professionalism":2},"result":"Você recebeu uma cobrança direta e útil.","reply_speaker":"Capitão","reply":"Pontualidade, treino sério e não sumir quando a fase aperta. O resto a gente constrói."},{"key":"prove","label":"Dizer que prefere provar no dia a dia do que falar.","effects":{"locker":1,"ambition":2,"teammate_relation":1},"result":"Você respondeu com postura competitiva.","reply_speaker":"Capitão","reply":"Perfeito. Então faz. Aqui ninguém precisa de discurso bonito."},{"key":"relax","label":"Dizer que o ambiente também precisa ser leve, não só cobrança.","effects":{"sociability":2,"locker":1,"teammate_relation":-1},"result":"Você trouxe outra visão para a conversa.","reply_speaker":"Capitão","reply":"Concordo. Leveza é boa. Só não pode virar relaxo quando começa a valer ponto."}]'::jsonb),
('mate_rival_challenge','Rival','“A vaga não é sua.”','O jogador que disputa posição com você diz, sem rodeios, que não pretende aceitar ficar atrás na hierarquia.',
 '[{"key":"respect","label":"Dizer que quer uma disputa forte e limpa.","effects":{"teammate_relation":3,"locker":1,"rivalry":-1,"ambition":1},"result":"A rivalidade ganhou respeito competitivo.","reply_speaker":"Rival","reply":"Então estamos entendidos. Quem estiver melhor joga. Sem desculpa."},{"key":"fire","label":"Responder que ele vai precisar correr muito para tirar sua vaga.","effects":{"teammate_relation":-7,"rivalry":1,"ego":2,"ambition":2},"result":"Você elevou a temperatura da disputa.","reply_speaker":"Rival","reply":"É disso que eu gosto. Guarda essa frase para depois do próximo treino."},{"key":"ignore","label":"Não alimentar a provocação.","effects":{"pressure":-1,"teammate_relation":-1},"result":"Você não entrou no confronto.","reply_speaker":"Rival","reply":"Silêncio também responde. A gente vê no campo."}]'::jsonb),
('mate_rival_respect','Rival','Respeito depois de uma disputa','Depois de uma sessão muito competitiva, seu rival reconhece que você elevou o nível do treino.',
 '[{"key":"return","label":"Reconhecer que ele também te força a melhorar.","effects":{"teammate_relation":6,"rivalry":-1,"locker":2,"professionalism":1},"result":"A rivalidade ficou mais saudável.","reply_speaker":"Rival","reply":"É isso. Eu quero sua vaga, mas prefiro ganhar de alguém que me faça melhorar."},{"key":"cold","label":"Agradecer de forma curta e seguir.","effects":{"teammate_relation":1,"rivalry":0},"result":"O respeito ficou implícito, sem aproximação.","reply_speaker":"Rival","reply":"Tá. Amanhã tem mais."},{"key":"taunt","label":"Dizer que ele só percebeu agora porque você está abrindo vantagem.","effects":{"teammate_relation":-5,"rivalry":1,"ego":2},"result":"O elogio virou nova provocação.","reply_speaker":"Rival","reply":"Não se empolga. Uma semana boa não ganha temporada."}]'::jsonb),
('mate_rival_contact','Rival','Dividida mais forte','Seu concorrente chega mais firme numa dividida e depois pergunta se você achou que ele passou do ponto.',
 '[{"key":"clean","label":"Dizer que faz parte da disputa e seguir treinando.","effects":{"teammate_relation":3,"rivalry":-1,"morale":1},"result":"Você tirou peso do lance.","reply_speaker":"Rival","reply":"Boa. Eu também não quero fazer ninguém se machucar. Só não vou aliviar."},{"key":"warn","label":"Avisar que intensidade não dá direito de colocar alguém em risco.","effects":{"teammate_relation":0,"locker":1,"discipline":2},"result":"Você colocou um limite sem recuar da disputa.","reply_speaker":"Rival","reply":"Justo. Se eu passar do ponto de novo, fala na hora."},{"key":"retaliate","label":"Dizer que na próxima dividida ele vai receber igual.","effects":{"teammate_relation":-8,"rivalry":1,"locker":-2,"discipline":-2},"result":"A tensão virou ameaça de revanche.","reply_speaker":"Rival","reply":"Então vamos ver quem recua primeiro."}]'::jsonb),
('mate_rival_media','Rival','Comparação na imprensa','Uma matéria comparou você diretamente com o jogador que disputa sua posição. Ele toca no assunto no vestiário.',
 '[{"key":"reject","label":"Dizer que a comparação de fora não muda a relação dentro do time.","effects":{"locker":3,"teammate_relation":4,"media":-1,"rivalry":-1},"result":"Você separou competição interna de narrativa externa.","reply_speaker":"Rival","reply":"Melhor assim. A imprensa precisa de história; a gente precisa jogar."},{"key":"embrace","label":"Dizer que a comparação é justa e que você quer mostrar que é melhor.","effects":{"fame":1,"media":2,"teammate_relation":-6,"rivalry":1,"ambition":2},"result":"Você abraçou publicamente a disputa.","reply_speaker":"Rival","reply":"Perfeito. Então não reclama quando eu responder do mesmo jeito."},{"key":"joke","label":"Brincar que pelo menos colocaram uma foto boa dos dois.","effects":{"sociability":2,"teammate_relation":2,"pressure":-1},"result":"A piada tirou parte do peso da comparação.","reply_speaker":"Rival","reply":"A sua estava melhor mesmo. No campo eu compenso."}]'::jsonb),
('mate_goal_drought_support','Companheiro','“O gol vai sair.”','Um atacante do elenco comenta que percebeu sua ansiedade para produzir números e diz que isso pode estar atrapalhando.',
 '[{"key":"listen","label":"Perguntar como ele lida com períodos sem gol ou assistência.","effects":{"pressure":-3,"teammate_relation":5,"professionalism":1,"skills":{"finishing_touch":1}},"result":"A conversa ajudou a colocar a fase em perspectiva.","reply_speaker":"Companheiro","reply":"Eu tento voltar para a jogada certa. Quando começo a caçar gol, normalmente jogo pior."},{"key":"confidence","label":"Dizer que não está preocupado e que os números vão aparecer.","effects":{"morale":2,"pressure":-1,"teammate_relation":1},"result":"Você reforçou confiança no próprio processo.","reply_speaker":"Companheiro","reply":"Então mantém. Eu só não queria ver você se cobrando por coisa que ainda vai acontecer."},{"key":"irritated","label":"Dizer que não precisa de conselho sobre seus números.","effects":{"teammate_relation":-4,"pressure":1,"ego":2},"result":"A tentativa de apoio terminou mal.","reply_speaker":"Companheiro","reply":"Beleza. Não falo mais. Boa sorte então."}]'::jsonb),
('mate_defensive_effort','Companheiro','Cobrança sem a bola','Um companheiro diz que, quando você perde a bola, espera que você ajude mais na recomposição.',
 '[{"key":"accept","label":"Aceitar a cobrança e perguntar onde ele precisa de cobertura.","effects":{"locker":3,"teammate_relation":5,"coach":1,"skills":{"positioning":2}},"result":"A cobrança virou alinhamento coletivo.","reply_speaker":"Companheiro","reply":"É só fechar por dentro primeiro. Se fizer isso, eu consigo sair na pressão sem deixar buraco."},{"key":"role","label":"Dizer que seu papel principal é criar e atacar.","effects":{"teammate_relation":-3,"ego":2,"locker":-1},"result":"Você defendeu uma visão mais individual da função.","reply_speaker":"Companheiro","reply":"Todo mundo tem função principal. Mas quando perde a bola, a gente defende com onze."},{"key":"coach","label":"Dizer que vai confirmar com o treinador exatamente o que ele quer.","effects":{"coach":2,"teammate_relation":1,"professionalism":2},"result":"Você levou a discussão para um critério objetivo.","reply_speaker":"Companheiro","reply":"Perfeito. Se ele disser que é diferente, eu ajusto também."}]'::jsonb),
('mate_private_confidence','Companheiro','Uma conversa mais pessoal','Um companheiro admite que está inseguro com a própria posição no elenco e pergunta se você já passou por algo parecido.',
 '[{"key":"support","label":"Compartilhar que também sente pressão e tentar apoiá-lo.","effects":{"teammate_relation":7,"locker":3,"leadership":2,"personal":1},"result":"A conversa criou confiança entre vocês.","reply_speaker":"Companheiro","reply":"Valeu. Às vezes parece que todo mundo aqui está seguro menos eu."},{"key":"competitive","label":"Dizer que insegurança faz parte e cada um precisa provar seu valor.","effects":{"ambition":2,"teammate_relation":-1,"leadership":1},"result":"Você respondeu de forma competitiva, sem muito acolhimento.","reply_speaker":"Companheiro","reply":"É... eu sei. Acho que eu esperava ouvir outra coisa, mas entendi."},{"key":"avoid","label":"Dizer que prefere não entrar em assuntos pessoais do elenco.","effects":{"teammate_relation":-4,"personal":2,"locker":-1},"result":"Você manteve uma fronteira clara.","reply_speaker":"Companheiro","reply":"Desculpa. Não devia ter jogado isso em cima de você."}]'::jsonb),
('mate_leadership_test','Companheiro','O grupo olha para você','Durante uma pequena discussão no treino, um companheiro pergunta de que lado você está e espera que você se posicione.',
 '[{"key":"mediate","label":"Tentar baixar o tom e encontrar um meio-termo.","effects":{"locker":4,"leadership":3,"teammate_relation":3,"pressure":1},"result":"Você assumiu uma postura de mediação.","reply_speaker":"Companheiro","reply":"Tá. Você tem razão. A gente resolve isso jogando, não gritando."},{"key":"side","label":"Tomar partido do companheiro com quem você concorda.","effects":{"teammate_relation":5,"locker":-1,"leadership":1},"result":"Você fortaleceu um vínculo e criou distância com o outro lado.","reply_speaker":"Companheiro","reply":"Valeu por falar. Pelo menos alguém viu a mesma coisa que eu."},{"key":"stay_out","label":"Dizer que não quer se envolver.","effects":{"pressure":-2,"leadership":-2},"result":"Você evitou o conflito, mas também abriu mão de influência.","reply_speaker":"Companheiro","reply":"Beleza. A gente resolve entre a gente então."}]'::jsonb),
('mate_routine_question','Companheiro','Como você está aguentando a rotina?','No caminho para o campo, um jogador pergunta como você está conciliando treino do clube, treino individual e descanso.',
 '[{"key":"balance","label":"Dizer que está tentando aprender a equilibrar carga e recuperação.","effects":{"professionalism":2,"teammate_relation":3,"discipline":1},"result":"A conversa reforçou uma postura madura sobre carga.","reply_speaker":"Companheiro","reply":"Demora para pegar o jeito. O erro é achar que treinar mais sempre significa evoluir mais."},{"key":"push","label":"Dizer que pretende treinar o máximo possível enquanto for jovem.","effects":{"ambition":3,"teammate_relation":1,"fatigue":1},"result":"Sua ambição ficou evidente.","reply_speaker":"Companheiro","reply":"Só escuta o corpo. Eu já vi gente perder mês inteiro tentando ganhar dois dias."},{"key":"relax","label":"Dizer que prefere não pensar demais e sentir o dia.","effects":{"morale":2,"discipline":-1,"teammate_relation":1},"result":"Você mostrou uma abordagem mais espontânea.","reply_speaker":"Companheiro","reply":"Também funciona. Só não deixa a semana decidir tudo por você."}]'::jsonb),
('mate_first_big_game','Companheiro','“Vai sentir quando chegar.”','Um companheiro fala sobre a pressão de um jogo importante e pergunta como você acha que vai reagir quando o estádio apertar.',
 '[{"key":"excited","label":"Dizer que é exatamente esse tipo de jogo que você quer viver.","effects":{"morale":3,"ambition":2,"pressure":2,"teammate_relation":2},"result":"Você demonstrou entusiasmo com a pressão.","reply_speaker":"Companheiro","reply":"Boa. Então usa isso. Só lembra de respirar quando a bola chegar pela primeira vez."},{"key":"calm","label":"Dizer que pretende tratar como qualquer outro jogo.","effects":{"pressure":-2,"professionalism":2,"teammate_relation":2},"result":"Você escolheu normalizar o momento.","reply_speaker":"Companheiro","reply":"Ajuda. Mas não se assusta se o corpo perceber antes da cabeça que o jogo é diferente."},{"key":"nervous","label":"Admitir que está nervoso e perguntar como ele controla isso.","effects":{"pressure":-3,"teammate_relation":5,"ego":-1},"result":"A honestidade abriu espaço para conselho.","reply_speaker":"Companheiro","reply":"Primeiros cinco minutos: faz o simples. Depois o jogo começa a parecer normal."}]'::jsonb),
('mate_contract_money','Companheiro','Dinheiro vira assunto','Num papo descontraído, um companheiro começa a comparar salários e pergunta quanto você conseguiu no contrato.',
 '[{"key":"share","label":"Falar o valor sem fazer mistério.","effects":{"teammate_relation":2,"sociability":2,"locker":-1},"result":"A conversa ficou aberta, mas comparação de salário entrou no ambiente.","reply_speaker":"Companheiro","reply":"Sério? Interessante. Cada negociação é um mundo mesmo."},{"key":"private","label":"Dizer que prefere manter salário e contrato em particular.","effects":{"personal":3,"teammate_relation":0,"professionalism":1},"result":"Você colocou um limite sem hostilidade.","reply_speaker":"Companheiro","reply":"Justo. Eu fui curioso. Deixa quieto."},{"key":"joke","label":"Brincar dizendo que ainda não ganha o suficiente para contar.","effects":{"sociability":3,"teammate_relation":2,"locker":1},"result":"Você desviou do assunto com humor.","reply_speaker":"Companheiro","reply":"Essa resposta foi boa. Vou usar quando perguntarem o meu."}]'::jsonb),
('mate_recovery_warning','Companheiro','“Você está com a perna pesada.”','Um jogador que treina perto de você comenta que sua movimentação parece mais pesada do que no começo da semana.',
 '[{"key":"listen","label":"Levar o comentário a sério e considerar reduzir carga.","effects":{"fatigue":-1,"teammate_relation":4,"professionalism":2},"result":"Você passou a observar o próprio corpo com mais atenção.","reply_speaker":"Companheiro","reply":"Eu só falei porque já fiquei fora por ignorar exatamente esse sinal."},{"key":"fine","label":"Dizer que está bem e que é só impressão.","effects":{"morale":1,"teammate_relation":0,"ambition":1},"result":"Você manteve seu plano sem mudar nada.","reply_speaker":"Companheiro","reply":"Tomara. Só não precisa provar nada para mim."},{"key":"annoyed","label":"Dizer que a comissão médica cuida disso e que ele não precisa se preocupar.","effects":{"teammate_relation":-4,"ego":1},"result":"O conselho foi recebido como intromissão.","reply_speaker":"Companheiro","reply":"Tá bom. Foi mal por comentar."}]'::jsonb)
ON CONFLICT(event_key) DO UPDATE SET source=EXCLUDED.source,title=EXCLUDED.title,body=EXCLUDED.body,choices=EXCLUDED.choices;

CREATE OR REPLACE FUNCTION private.pick_teammate_dialogue_event(p_player_id uuid,p_teammate_id uuid,p_activity_key text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_relation int:=50; v_rival boolean:=false; v_same_position boolean:=false; v_form int:=50; v_pressure int:=25;
  v_candidates text[]; v_recent text[]; v_available text[]; v_key text;
BEGIN
  SELECT coalesce(r.relation,50),coalesce(r.rivalry,false),(ai.primary_position=j.posicao),coalesce(pcs.form,50),coalesce(pcs.pressure,25)
  INTO v_relation,v_rival,v_same_position,v_form,v_pressure
  FROM public.player_teammate_relations r
  JOIN public.base_ai_players ai ON ai.id=r.teammate_id
  JOIN public.jogadores j ON j.id=r.player_id
  JOIN public.player_career_state pcs ON pcs.player_id=r.player_id
  WHERE r.player_id=p_player_id AND r.teammate_id=p_teammate_id;

  IF v_rival OR v_relation<=34 THEN
    v_candidates:=ARRAY['mate_rival_challenge','mate_rival_respect','mate_rival_contact','mate_rival_media','mate_pass_complaint','mate_defensive_effort'];
  ELSIF v_same_position THEN
    v_candidates:=ARRAY['mate_rival_challenge','mate_penalty_talker','mate_tactical_disagreement','mate_training_tip','mate_extra_session_invite','mate_media_jealousy'];
  ELSIF v_pressure>=55 OR v_form<=42 THEN
    v_candidates:=ARRAY['mate_support_bad_week','mate_goal_drought_support','mate_private_confidence','mate_mentor_advice','mate_recovery_warning','mate_first_big_game'];
  ELSIF p_activity_key IN ('team_training_intense','team_training_normal','team_training_light','teammate_extra','watch_match_analysis') THEN
    v_candidates:=ARRAY['mate_training_tip','mate_extra_session_invite','mate_tactical_disagreement','mate_defensive_effort','mate_recovery_warning','mate_routine_question','mate_ask_help'];
  ELSIF v_relation>=70 THEN
    v_candidates:=ARRAY['mate_social_invite','mate_prank','mate_social_post','mate_private_confidence','mate_ask_help','mate_music_room','mate_contract_money'];
  ELSE
    v_candidates:=ARRAY['mate_training_tip','mate_social_invite','mate_prank','mate_media_jealousy','mate_agent_rumor','mate_mentor_advice','mate_ask_help','mate_music_room','mate_social_post','mate_captain_standard','mate_leadership_test','mate_routine_question','mate_contract_money','mate_first_big_game'];
  END IF;

  SELECT coalesce(array_agg(event_key),'{}'::text[]) INTO v_recent
  FROM (
    SELECT event_key FROM public.player_career_events
    WHERE player_id=p_player_id AND status='resolved'
    ORDER BY created_at DESC LIMIT 6
  ) x;

  SELECT coalesce(array_agg(c),'{}'::text[]) INTO v_available
  FROM unnest(v_candidates)c
  WHERE NOT (c=ANY(v_recent));
  IF cardinality(v_available)=0 THEN v_available:=v_candidates; END IF;
  v_key:=v_available[1+floor(random()*cardinality(v_available))::int];
  RETURN v_key;
END;
$$;

-- O motor existente ainda decide QUANDO uma conversa deve acontecer. Este trigger
-- apenas troca os dois diálogos genéricos por um diálogo contextual, depois do sorteio.
CREATE OR REPLACE FUNCTION private.rewrite_generic_teammate_dialogue()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_event record; v_teammate uuid; v_key text; v_template record; v_name text;
BEGIN
  SELECT e.* INTO v_event
  FROM public.player_career_events e
  WHERE e.player_id=NEW.player_id AND e.status='pending'
    AND e.event_key IN ('teammate_locker_room','rival_training_tension')
    AND e.metadata->>'kind'='teammate_interaction'
  ORDER BY e.created_at DESC LIMIT 1;
  IF v_event.id IS NULL THEN RETURN NEW; END IF;

  v_teammate:=nullif(v_event.metadata->>'teammate_id','')::uuid;
  IF v_teammate IS NULL THEN RETURN NEW; END IF;
  v_key:=private.pick_teammate_dialogue_event(NEW.player_id,v_teammate,NEW.activity_key);
  SELECT * INTO v_template FROM private.career_event_templates WHERE event_key=v_key;
  SELECT name INTO v_name FROM public.base_ai_players WHERE id=v_teammate;
  IF v_template.event_key IS NULL THEN RETURN NEW; END IF;

  UPDATE public.player_career_events
  SET event_key=v_key,
      source=coalesce(v_name,v_template.source),
      title=v_template.title,
      body=v_template.body,
      metadata=metadata||jsonb_build_object('dialogue_engine','v2','activity',NEW.activity_key)
  WHERE id=v_event.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_after_career_action_zz_teammate_dialogue ON public.player_career_actions;
CREATE TRIGGER trg_after_career_action_zz_teammate_dialogue
AFTER INSERT ON public.player_career_actions
FOR EACH ROW EXECUTE FUNCTION private.rewrite_generic_teammate_dialogue();

COMMIT;
