BEGIN;

-- Clubs generated by the competition world receive 22 AI players. The seed in
-- 1030 used slot <= 11 as a starter shortcut, which could put two goalkeepers
-- in the XI and leave attackers on the bench. Rebuild only the newly generated
-- club squads by football role, preserving established legacy youth squads.
WITH generated AS (
  SELECT
    p.id,
    p.club_id,
    p.primary_position,
    p.ovr,
    row_number() OVER (
      PARTITION BY p.club_id,p.primary_position
      ORDER BY p.ovr DESC,p.id
    ) AS pos_rank,
    CASE p.primary_position
      WHEN 'Goleiro' THEN 'gk'
      WHEN 'Lateral Direito' THEN 'rb'
      WHEN 'Lateral Esquerdo' THEN 'lb'
      WHEN 'Zagueiro' THEN 'cb'
      WHEN 'Volante' THEN 'dm'
      WHEN 'Meio-Campo' THEN 'mid'
      WHEN 'Meia Direita' THEN 'mid'
      WHEN 'Meia Esquerda' THEN 'mid'
      WHEN 'Ponta Direita' THEN 'rw'
      WHEN 'Ponta Esquerda' THEN 'lw'
      WHEN 'Atacante' THEN 'st'
      ELSE 'other'
    END AS role_group
  FROM public.base_ai_players p
  JOIN public.base_clubs c ON c.id=p.club_id
  WHERE c.club_code LIKE 'PRO\_%' ESCAPE '\'
     OR c.club_code LIKE 'Y\_NEW\_%' ESCAPE '\'
),
mid_ranked AS (
  SELECT
    g.*,
    CASE WHEN g.role_group='mid' THEN
      row_number() OVER (
        PARTITION BY g.club_id,g.role_group
        ORDER BY g.ovr DESC,g.id
      )
    END AS group_rank
  FROM generated g
),
selected AS (
  SELECT
    id,
    club_id,
    CASE
      WHEN role_group='gk' AND pos_rank=1 THEN true
      WHEN role_group='rb' AND pos_rank=1 THEN true
      WHEN role_group='lb' AND pos_rank=1 THEN true
      WHEN role_group='cb' AND pos_rank<=2 THEN true
      WHEN role_group='dm' AND pos_rank=1 THEN true
      WHEN role_group='mid' AND group_rank<=2 THEN true
      WHEN role_group='rw' AND pos_rank=1 THEN true
      WHEN role_group='lw' AND pos_rank=1 THEN true
      WHEN role_group='st' AND pos_rank=1 THEN true
      ELSE false
    END AS starter
  FROM mid_ranked
)
UPDATE public.base_ai_players p
SET is_starter=s.starter,
    squad_role=CASE WHEN s.starter THEN 'Titular' ELSE 'Reserva' END
FROM selected s
WHERE p.id=s.id;

-- Promote the six strongest non-starters to rotation; everyone else stays reserve.
WITH bench_rank AS (
  SELECT
    p.id,
    row_number() OVER (
      PARTITION BY p.club_id
      ORDER BY p.ovr DESC,p.id
    ) AS rn
  FROM public.base_ai_players p
  JOIN public.base_clubs c ON c.id=p.club_id
  WHERE NOT p.is_starter
    AND (c.club_code LIKE 'PRO\_%' ESCAPE '\' OR c.club_code LIKE 'Y\_NEW\_%' ESCAPE '\')
)
UPDATE public.base_ai_players p
SET squad_role=CASE WHEN b.rn<=6 THEN 'Rotação' ELSE 'Reserva' END
FROM bench_rank b
WHERE p.id=b.id;

-- Give every generated squad 22 stable, unique shirt numbers. Role ordering
-- keeps traditional numbers broadly sensible without tying gameplay to them.
WITH numbered AS (
  SELECT
    p.id,
    p.club_id,
    row_number() OVER (
      PARTITION BY p.club_id
      ORDER BY
        CASE
          WHEN p.is_starter AND p.primary_position='Goleiro' THEN 1
          WHEN p.is_starter AND p.primary_position='Lateral Direito' THEN 2
          WHEN p.is_starter AND p.primary_position='Zagueiro' THEN 3
          WHEN p.is_starter AND p.primary_position='Lateral Esquerdo' THEN 4
          WHEN p.is_starter AND p.primary_position='Volante' THEN 5
          WHEN p.is_starter AND p.primary_position IN('Meio-Campo','Meia Direita','Meia Esquerda') THEN 6
          WHEN p.is_starter AND p.primary_position='Ponta Direita' THEN 8
          WHEN p.is_starter AND p.primary_position='Atacante' THEN 9
          WHEN p.is_starter AND p.primary_position='Ponta Esquerda' THEN 11
          WHEN p.primary_position='Goleiro' THEN 12
          ELSE 20
        END,
        p.ovr DESC,
        p.id
    ) AS rn
  FROM public.base_ai_players p
  JOIN public.base_clubs c ON c.id=p.club_id
  WHERE c.club_code LIKE 'PRO\_%' ESCAPE '\'
     OR c.club_code LIKE 'Y\_NEW\_%' ESCAPE '\'
),
shirts AS (
  SELECT
    id,
    (ARRAY[1,2,3,4,5,6,8,10,7,9,11,12,13,14,15,16,17,18,19,20,21,22])[rn] AS shirt_number
  FROM numbered
)
UPDATE public.base_ai_players p
SET squad_number=s.shirt_number
FROM shirts s
WHERE p.id=s.id;

-- Fail early if a generated club does not have the expected football squad.
DO $$
DECLARE
  v_bad record;
BEGIN
  SELECT
    c.id,
    c.name,
    count(p.id) AS players,
    count(*) FILTER(WHERE p.is_starter) AS starters,
    count(*) FILTER(WHERE p.is_starter AND p.primary_position='Goleiro') AS starter_gk,
    count(*) FILTER(WHERE p.is_starter AND p.primary_position IN('Ponta Direita','Ponta Esquerda','Atacante')) AS starter_attack,
    count(DISTINCT p.squad_number) AS shirt_numbers
  INTO v_bad
  FROM public.base_clubs c
  JOIN public.base_ai_players p ON p.club_id=c.id
  WHERE c.club_code LIKE 'PRO\_%' ESCAPE '\'
     OR c.club_code LIKE 'Y\_NEW\_%' ESCAPE '\'
  GROUP BY c.id,c.name
  HAVING count(p.id)<>22
      OR count(*) FILTER(WHERE p.is_starter)<>11
      OR count(*) FILTER(WHERE p.is_starter AND p.primary_position='Goleiro')<>1
      OR count(*) FILTER(WHERE p.is_starter AND p.primary_position IN('Ponta Direita','Ponta Esquerda','Atacante'))<3
      OR count(DISTINCT p.squad_number)<>22
  LIMIT 1;

  IF v_bad.id IS NOT NULL THEN
    RAISE EXCEPTION 'Elenco gerado inválido em %: jogadores %, titulares %, GK titular %, atacantes titulares %, camisas únicas %.',
      v_bad.name,v_bad.players,v_bad.starters,v_bad.starter_gk,v_bad.starter_attack,v_bad.shirt_numbers;
  END IF;
END $$;

COMMIT;
