INSERT INTO private.career_activity_catalog
(activity_key,category,title,description,icon,load_label,supports_intensity,supports_duration,base_duration,energy_delta,fatigue_delta,morale_delta,trust_delta,form_delta,media_delta,fan_delta,locker_delta,board_delta,agent_delta,image_delta,personal_delta,pressure_delta,cash_delta,skill_effects,base_injury_risk,result_summary,event_key)
VALUES
('penalty_practice','training','Treino de pênaltis','Repita cobranças com rotinas diferentes de aproximação e escolha de canto.','circle-dot','Baixa',true,true,30,-5,1,1,0,1,0,0,0,0,0,0,0,0,0,'{"penalties":18,"finishing_touch":3}',1,'Você trabalhou repetição e confiança nas cobranças de pênalti.',NULL),
('heading_session','training','Cabeceio e jogo aéreo','Trabalhe impulsão, tempo de bola e direção das cabeçadas.','move-up','Moderada',true,true,60,-10,4,0,0,1,0,0,0,0,0,0,0,1,0,'{"heading":17,"strength":3}',3,'Você completou uma sessão focada em jogo aéreo.',NULL),
('defensive_session','training','Marcação e duelos','Pratique abordagem, distância, cobertura e recuperação da bola.','shield-check','Moderada',true,true,60,-10,4,0,0,1,0,0,0,0,0,0,0,1,0,'{"marking":16,"tactical_awareness":5}',3,'Você trabalhou marcação e leitura defensiva.',NULL),
('endurance','training','Resistência','Faça um trabalho contínuo para sustentar intensidade durante períodos mais longos.','timer-reset','Alta',true,true,60,-16,9,0,0,1,0,0,0,0,0,0,0,2,0,'{"stamina":20,"sprint":3}',5,'Você completou uma sessão pesada de resistência.',NULL),
('teammate_extra','training','Treino extra com companheiro','Convide um jogador do elenco para uma sessão técnica fora do treino coletivo.','users-round','Moderada',true,true,60,-9,4,3,0,1,0,0,5,0,0,0,1,0,0,'{"short_pass":7,"dribbling":7,"positioning":4}',2,'Você fez um trabalho extra junto de um companheiro.',NULL),
('mobility','recovery','Mobilidade e alongamento','Faça uma sessão leve de mobilidade para aliviar tensão sem ficar totalmente parado.','accessibility','Baixa',false,false,45,4,-6,1,0,0,0,0,0,0,0,0,0,-1,0,'{"stamina":2}',0,'Você fez um trabalho leve de mobilidade e soltura muscular.',NULL),
('sports_psychologist','recovery','Psicólogo esportivo','Use o período para trabalhar pressão, confiança e rotina mental com acompanhamento profissional.','brain-circuit','Baixa',false,false,60,0,0,7,0,0,0,0,0,0,0,0,3,-10,-280,'{}',0,'Você conversou sobre pressão, expectativas e rotina mental.',NULL),
('nutrition_session','recovery','Nutrição e preparação','Organize alimentação e recuperação do dia com acompanhamento individual.','salad','Baixa',false,false,45,7,-3,2,0,0,0,0,0,0,0,0,0,-2,-90,'{}',0,'Você dedicou o período à preparação alimentar e recuperação.',NULL),
('fan_meet','professional','Encontro com torcedores','Participe de uma ação do clube com jovens e torcedores da região.','megaphone','Baixa',false,false,60,-4,1,3,0,0,1,7,0,4,0,4,1,2,0,'{}',0,'Você participou de uma atividade próxima da torcida.',NULL),
('community_action','professional','Ação comunitária','Represente o clube em uma atividade social fora do centro de treinamento.','hand-heart','Baixa',false,false,60,-5,1,4,0,0,2,4,1,5,0,5,2,1,0,'{}',0,'Você representou o clube em uma ação comunitária.',NULL),
('social_media_post','professional','Publicar nas redes','Escolha como se posicionar publicamente em um momento comum da semana.','smartphone','Baixa',false,false,30,-1,0,0,0,0,1,0,0,0,0,2,0,1,0,'{}',0,'Você reservou um tempo para cuidar da sua presença pública.','social_media_tone')
ON CONFLICT(activity_key) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,description=EXCLUDED.description,icon=EXCLUDED.icon,load_label=EXCLUDED.load_label,supports_intensity=EXCLUDED.supports_intensity,supports_duration=EXCLUDED.supports_duration,base_duration=EXCLUDED.base_duration,energy_delta=EXCLUDED.energy_delta,fatigue_delta=EXCLUDED.fatigue_delta,morale_delta=EXCLUDED.morale_delta,trust_delta=EXCLUDED.trust_delta,form_delta=EXCLUDED.form_delta,media_delta=EXCLUDED.media_delta,fan_delta=EXCLUDED.fan_delta,locker_delta=EXCLUDED.locker_delta,board_delta=EXCLUDED.board_delta,agent_delta=EXCLUDED.agent_delta,image_delta=EXCLUDED.image_delta,personal_delta=EXCLUDED.personal_delta,pressure_delta=EXCLUDED.pressure_delta,cash_delta=EXCLUDED.cash_delta,skill_effects=EXCLUDED.skill_effects,base_injury_risk=EXCLUDED.base_injury_risk,result_summary=EXCLUDED.result_summary,event_key=EXCLUDED.event_key;

INSERT INTO private.career_event_templates(event_key,source,title,body,choices) VALUES
('social_media_tone','Redes sociais','O que você quer publicar?','Seu assessor deixou três ideias prontas. Você também pode optar por uma mensagem simples e evitar transformar a publicação em assunto.','[{"key":"team","label":"“Semana de trabalho com o grupo. Seguimos juntos.”","result":"A publicação reforçou uma imagem ligada ao coletivo.","effects":{"fans":2,"locker":3,"board":2,"image":1,"media":-1}},{"key":"ambitious","label":"“Trabalhando em silêncio. Meu objetivo é chegar ao topo.”","result":"A mensagem aumentou a atenção sobre sua ambição pessoal.","effects":{"media":3,"image":4,"agent":2,"fans":1,"locker":-1,"pressure":3,"ambition":2}},{"key":"provocative","label":"“Podem falar. Eu sei o que sou capaz de fazer.”","result":"A frase ganhou repercussão e dividiu a reação em torno do seu nome.","effects":{"media":6,"fans":4,"image":5,"coach":-2,"board":-2,"locker":-2,"pressure":5,"ego":3}},{"key":"simple","label":"“Mais um dia. 🙏”","result":"A publicação passou quase sem ruído e manteve sua exposição controlada.","effects":{"media":-1,"fans":1,"image":1,"pressure":-1}}]')
ON CONFLICT(event_key) DO UPDATE SET source=EXCLUDED.source,title=EXCLUDED.title,body=EXCLUDED.body,choices=EXCLUDED.choices;
