-- Career Hub: rotina, treino, estafa, relações, progressão e decisões pré-partida.
-- A partida não é simulada aqui: o relógio para quando chega ao jogo.

CREATE SCHEMA IF NOT EXISTS private;

ALTER TABLE public.player_career_state
  ADD COLUMN IF NOT EXISTS fatigue INT NOT NULL DEFAULT 18 CHECK (fatigue BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS form INT NOT NULL DEFAULT 50 CHECK (form BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS cash_balance INT NOT NULL DEFAULT 0 CHECK (cash_balance >= 0),
  ADD COLUMN IF NOT EXISTS career_date DATE,
  ADD COLUMN IF NOT EXISTS day_period SMALLINT NOT NULL DEFAULT 0 CHECK (day_period BETWEEN 0 AND 2),
  ADD COLUMN IF NOT EXISTS next_match_date DATE,
  ADD COLUMN IF NOT EXISTS media_relation INT NOT NULL DEFAULT 50 CHECK (media_relation BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS fan_relation INT NOT NULL DEFAULT 50 CHECK (fan_relation BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS locker_room_relation INT NOT NULL DEFAULT 50 CHECK (locker_room_relation BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS board_relation INT NOT NULL DEFAULT 50 CHECK (board_relation BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS agent_relation INT NOT NULL DEFAULT 55 CHECK (agent_relation BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS public_image INT NOT NULL DEFAULT 45 CHECK (public_image BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS personal_life INT NOT NULL DEFAULT 60 CHECK (personal_life BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS pressure INT NOT NULL DEFAULT 25 CHECK (pressure BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS injury_status TEXT NOT NULL DEFAULT 'healthy' CHECK (injury_status IN ('healthy','minor')),
  ADD COLUMN IF NOT EXISTS injury_label TEXT,
  ADD COLUMN IF NOT EXISTS injury_days INT NOT NULL DEFAULT 0 CHECK (injury_days BETWEEN 0 AND 60),
  ADD COLUMN IF NOT EXISTS personality JSONB NOT NULL DEFAULT '{"professionalism":50,"ambition":50,"leadership":40,"discipline":50,"sociability":50,"ego":45}'::jsonb,
  ADD COLUMN IF NOT EXISTS weekly_objective JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_salary_date DATE;

CREATE TABLE IF NOT EXISTS public.player_skill_development (
  player_id UUID NOT NULL REFERENCES public.jogadores(id) ON DELETE CASCADE,
  skill_key TEXT NOT NULL,
  label TEXT NOT NULL,
  category TEXT NOT NULL,
  parent_attribute TEXT NOT NULL,
  level INT NOT NULL CHECK (level BETWEEN 1 AND 99),
  progress NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress < 100),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (player_id, skill_key)
);

CREATE TABLE IF NOT EXISTS public.player_career_actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id UUID NOT NULL REFERENCES public.jogadores(id) ON DELETE CASCADE,
  career_date DATE NOT NULL,
  day_period SMALLINT NOT NULL CHECK (day_period BETWEEN 0 AND 2),
  activity_key TEXT NOT NULL,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  intensity TEXT,
  duration_minutes INT,
  result_summary TEXT NOT NULL,
  hidden_effects JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_player_career_actions_player_date ON public.player_career_actions(player_id, career_date DESC, day_period DESC);

CREATE TABLE IF NOT EXISTS public.player_career_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id UUID NOT NULL REFERENCES public.jogadores(id) ON DELETE CASCADE,
  event_key TEXT NOT NULL,
  source TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  choices JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','resolved','expired')),
  chosen_key TEXT,
  result_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_player_career_events_player_status ON public.player_career_events(player_id, status, created_at DESC);

ALTER TABLE public.player_skill_development ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_career_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_career_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.player_skill_development FROM anon, authenticated;
REVOKE ALL ON TABLE public.player_career_actions FROM anon, authenticated;
REVOKE ALL ON TABLE public.player_career_events FROM anon, authenticated;
GRANT SELECT ON TABLE public.player_skill_development TO authenticated;
GRANT SELECT ON TABLE public.player_career_actions TO authenticated;
GRANT SELECT ON TABLE public.player_career_events TO authenticated;
DROP POLICY IF EXISTS "Owner Skill Development Select" ON public.player_skill_development;
CREATE POLICY "Owner Skill Development Select" ON public.player_skill_development FOR SELECT TO authenticated USING (public.is_player_owner(player_id));
DROP POLICY IF EXISTS "Owner Career Actions Select" ON public.player_career_actions;
CREATE POLICY "Owner Career Actions Select" ON public.player_career_actions FOR SELECT TO authenticated USING (public.is_player_owner(player_id));
DROP POLICY IF EXISTS "Owner Career Events Select" ON public.player_career_events;
CREATE POLICY "Owner Career Events Select" ON public.player_career_events FOR SELECT TO authenticated USING (public.is_player_owner(player_id));

CREATE TABLE IF NOT EXISTS private.career_activity_catalog (
  activity_key TEXT PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('training','recovery','social','professional')),
  title TEXT NOT NULL, description TEXT NOT NULL, icon TEXT NOT NULL, load_label TEXT NOT NULL,
  supports_intensity BOOLEAN NOT NULL DEFAULT false, supports_duration BOOLEAN NOT NULL DEFAULT false,
  base_duration INT NOT NULL DEFAULT 60,
  energy_delta INT NOT NULL DEFAULT 0, fatigue_delta INT NOT NULL DEFAULT 0, morale_delta INT NOT NULL DEFAULT 0,
  trust_delta INT NOT NULL DEFAULT 0, form_delta INT NOT NULL DEFAULT 0, media_delta INT NOT NULL DEFAULT 0,
  fan_delta INT NOT NULL DEFAULT 0, locker_delta INT NOT NULL DEFAULT 0, board_delta INT NOT NULL DEFAULT 0,
  agent_delta INT NOT NULL DEFAULT 0, image_delta INT NOT NULL DEFAULT 0, personal_delta INT NOT NULL DEFAULT 0,
  pressure_delta INT NOT NULL DEFAULT 0, cash_delta INT NOT NULL DEFAULT 0,
  skill_effects JSONB NOT NULL DEFAULT '{}'::jsonb, base_injury_risk INT NOT NULL DEFAULT 0,
  result_summary TEXT NOT NULL, event_key TEXT
);

INSERT INTO private.career_activity_catalog
(activity_key,category,title,description,icon,load_label,supports_intensity,supports_duration,base_duration,energy_delta,fatigue_delta,morale_delta,trust_delta,form_delta,media_delta,fan_delta,locker_delta,board_delta,agent_delta,image_delta,personal_delta,pressure_delta,cash_delta,skill_effects,base_injury_risk,result_summary,event_key)
VALUES
('dribble_session','training','Treino de drible','Trabalhe condução, mudança de direção e domínio no um contra um.','route','Moderada',true,true,60,-10,4,1,0,1,0,0,0,0,0,0,0,1,0,'{"dribbling":14}',2,'Você terminou uma sessão focada em drible e controle de bola.',NULL),
('free_kicks','training','Bolas paradas','Repita faltas de diferentes distâncias e ângulos para ganhar precisão.','target','Baixa',true,true,60,-7,2,1,0,1,0,0,0,0,0,0,0,0,0,'{"free_kicks":16}',1,'Você trabalhou bola parada e repetição técnica.',NULL),
('finishing','training','Finalização','Treine definição rápida, chute colocado e conclusão sob pressão.','crosshair','Moderada',true,true,60,-11,4,1,0,1,0,0,0,0,0,0,0,1,0,'{"finishing_touch":14,"penalties":3}',2,'Você encerrou uma sessão de finalização.',NULL),
('passing','training','Passe e criação','Trabalhe passe curto, inversões e leitura antes de receber a bola.','send','Baixa',true,true,60,-8,3,1,0,1,0,0,0,0,0,0,0,0,0,'{"short_pass":10,"long_pass":8,"crossing":5}',1,'Você treinou passe e tomada de decisão.',NULL),
('sprint','training','Sprint e explosão','Séries curtas de aceleração para trabalhar potência e velocidade máxima.','zap','Alta',true,true,60,-15,8,0,0,1,0,0,0,0,0,0,0,2,0,'{"sprint":18,"stamina":4}',5,'Você completou um trabalho exigente de velocidade.',NULL),
('strength','training','Força na academia','Sessão de força para melhorar contato, estabilidade e potência.','dumbbell','Alta',true,true,60,-14,8,0,0,1,0,0,0,0,0,0,0,2,0,'{"strength":17,"heading":4}',4,'Você concluiu uma sessão de força.',NULL),
('tactical_study','training','Estudo tático','Reveja movimentos, posicionamento e padrões do seu setor em vídeo.','brain','Baixa',false,true,60,-3,0,0,1,1,0,0,0,0,0,0,0,-1,0,'{"positioning":10,"tactical_awareness":12}',0,'Você passou um período estudando situações táticas.',NULL),
('sauna','recovery','Sauna e regeneração','Use o centro de recuperação para aliviar a carga acumulada.','waves','Baixa',false,false,60,6,-9,3,0,0,0,0,0,0,0,0,1,-2,-120,'{}',0,'A sessão de recuperação ajudou seu corpo a desacelerar.',NULL),
('physio','recovery','Fisioterapia','Faça tratamento preventivo e trabalho muscular individual com a equipe médica.','heart-pulse','Baixa',false,false,60,4,-12,1,0,0,0,0,0,0,0,0,0,-1,-350,'{}',0,'Você passou pela fisioterapia e deixou o corpo mais preparado.',NULL),
('rest_home','recovery','Descansar em casa','Abra mão do período para recuperar o corpo e ficar longe da rotina do clube.','house','Baixa',false,false,60,14,-7,1,0,0,0,0,0,0,0,0,1,-2,0,'{}',0,'Você usou o período para descansar sem compromissos.',NULL),
('early_sleep','recovery','Dormir mais cedo','Encerre o dia antes e priorize uma noite de recuperação completa.','moon','Baixa',false,false,60,11,-5,1,0,0,0,0,0,0,0,0,0,-2,0,'{}',0,'Você priorizou o sono e a recuperação.',NULL),
('gaming_friends','social','Jogar com os amigos','Desconecte do futebol por algumas horas e alivie a cabeça.','gamepad-2','Baixa',false,false,60,-3,1,8,0,0,0,0,0,0,0,0,6,-5,0,'{}',0,'Você passou um tempo descontraído com amigos.',NULL),
('family_time','social','Tempo com a família','Passe o período com pessoas próximas e saia da pressão do futebol.','heart','Baixa',false,false,60,3,-1,7,0,0,0,0,0,0,0,0,8,-6,0,'{}',0,'Você recarregou a cabeça perto da família.',NULL),
('team_hangout','social','Sair com companheiros','Aceite um convite do elenco e fortaleça laços fora do centro de treinamento.','users','Baixa',false,false,60,-4,1,6,0,0,0,0,8,0,0,0,4,-3,0,'{}',0,'Você passou um tempo com companheiros do elenco.',NULL),
('night_out','social','Sair à noite','Uma noite fora pode aliviar a pressão, mas mexe com sua preparação.','music','Alta',false,false,60,-12,7,12,-1,0,2,1,1,-1,0,2,6,-8,-180,'{}',2,'Você aproveitou a noite longe do futebol.','night_out_spotted'),
('media_interview','professional','Falar com a imprensa','Aceite uma entrevista e escolha como quer se posicionar publicamente.','mic-2','Baixa',false,false,45,-1,0,0,0,0,2,0,0,0,0,2,0,2,0,'{}',0,'Você abriu espaço na agenda para conversar com a imprensa.','media_adaptation'),
('sponsor_event','professional','Evento de patrocinador','Participe de uma ação comercial ligada ao clube e à sua imagem.','badge-dollar-sign','Baixa',false,false,60,-3,1,2,0,0,2,1,0,3,0,5,0,2,450,'{}',0,'Você cumpriu um compromisso comercial e ganhou exposição.','sponsor_quote'),
('agent_meeting','professional','Conversar com o empresário','Discuta oportunidades, expectativas e os próximos passos da carreira.','briefcase-business','Baixa',false,false,60,-2,0,1,0,0,1,0,0,-1,7,1,0,1,0,'{}',0,'Você alinhou os próximos passos com seu empresário.','career_ambition'),
('watch_match_analysis','professional','Analisar futebol','Assista a jogos e reveja situações da sua posição com olhar profissional.','monitor-play','Baixa',false,true,60,-2,0,0,0,1,0,0,0,0,0,0,0,-1,0,'{"positioning":8,"tactical_awareness":9}',0,'Você usou o período para estudar futebol e padrões de jogo.',NULL)
ON CONFLICT (activity_key) DO UPDATE SET category=EXCLUDED.category,title=EXCLUDED.title,description=EXCLUDED.description,icon=EXCLUDED.icon,load_label=EXCLUDED.load_label,supports_intensity=EXCLUDED.supports_intensity,supports_duration=EXCLUDED.supports_duration,base_duration=EXCLUDED.base_duration,energy_delta=EXCLUDED.energy_delta,fatigue_delta=EXCLUDED.fatigue_delta,morale_delta=EXCLUDED.morale_delta,trust_delta=EXCLUDED.trust_delta,form_delta=EXCLUDED.form_delta,media_delta=EXCLUDED.media_delta,fan_delta=EXCLUDED.fan_delta,locker_delta=EXCLUDED.locker_delta,board_delta=EXCLUDED.board_delta,agent_delta=EXCLUDED.agent_delta,image_delta=EXCLUDED.image_delta,personal_delta=EXCLUDED.personal_delta,pressure_delta=EXCLUDED.pressure_delta,cash_delta=EXCLUDED.cash_delta,skill_effects=EXCLUDED.skill_effects,base_injury_risk=EXCLUDED.base_injury_risk,result_summary=EXCLUDED.result_summary,event_key=EXCLUDED.event_key;

CREATE TABLE IF NOT EXISTS private.career_event_templates (event_key TEXT PRIMARY KEY,source TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,choices JSONB NOT NULL);
INSERT INTO private.career_event_templates(event_key,source,title,body,choices) VALUES
('arrival_dressing_room','Vestiário','Primeiro contato com o elenco','O capitão se aproxima depois da apresentação e pergunta como você quer chegar ao grupo.','[{"key":"humble","label":"“Vim para aprender e ajudar no que precisarem.”","result":"A postura tranquila foi bem recebida no primeiro contato.","effects":{"locker":5,"coach":2,"image":1,"ambition":-1}},{"key":"confident","label":"“Quero conquistar meu espaço o mais rápido possível.”","result":"Sua confiança chamou atenção — para o bem e para o mal.","effects":{"locker":-1,"coach":1,"fans":2,"image":3,"ambition":4,"ego":2}},{"key":"quiet","label":"“Prefiro mostrar no campo.”","result":"Você manteve distância e deixou a primeira impressão em aberto.","effects":{"locker":-2,"coach":1,"media":-1,"discipline":2}}]'),
('media_adaptation','Imprensa','Primeiras palavras no novo clube','Um repórter pergunta se você espera ser protagonista rapidamente no novo clube.','[{"key":"team_first","label":"“O mais importante é o time. Meu espaço vai chegar com trabalho.”","result":"A resposta passou segurança e espírito de grupo.","effects":{"media":1,"fans":3,"locker":3,"coach":2,"image":1}},{"key":"ambitious","label":"“Eu vim para jogar. Quero mostrar que mereço ser titular.”","result":"A declaração ganhou manchetes e aumentou a expectativa sobre você.","effects":{"media":6,"fans":2,"coach":-2,"locker":-2,"board":-1,"agent":3,"image":4,"pressure":6,"ambition":4}},{"key":"direct","label":"“Se eu estiver melhor, espero jogar. Futebol é rendimento.”","result":"A sinceridade dividiu opiniões dentro e fora do clube.","effects":{"media":5,"fans":4,"coach":-4,"locker":-3,"image":3,"pressure":4,"ego":3}},{"key":"no_comment","label":"“Ainda é cedo. Prefiro não criar expectativa.”","result":"Você evitou a manchete, mas também não alimentou entusiasmo.","effects":{"media":-3,"fans":-1,"coach":1,"image":-1,"pressure":-2}}]'),
('career_ambition','Empresário','Qual é sua prioridade?','Seu empresário pergunta que tipo de movimento deve priorizar quando surgirem oportunidades.','[{"key":"minutes","label":"“Quero jogar. Não adianta ir para um clube maior e ficar no banco.”","result":"Seu empresário entendeu que minutos terão prioridade nas próximas conversas.","effects":{"agent":3,"board":1,"fans":2,"ambition":-1,"professionalism":2}},{"key":"big_club","label":"“Se aparecer um clube grande, quero saber na hora.”","result":"Seu empresário vai trabalhar sua exposição de forma mais agressiva.","effects":{"agent":5,"board":-3,"fans":-3,"media":3,"image":2,"pressure":3,"ambition":5}},{"key":"money","label":"“Quero valorizar meu contrato. A parte financeira importa.”","result":"A conversa ficou mais comercial e objetiva.","effects":{"agent":4,"board":-2,"fans":-4,"image":1,"ambition":3,"ego":2}},{"key":"stay","label":"“Não quero pensar em sair agora.”","result":"A mensagem de estabilidade tende a repercutir bem internamente.","effects":{"agent":-1,"board":4,"fans":5,"coach":2,"locker":2,"pressure":-2}}]'),
('night_out_spotted','Mídia','Uma foto começa a circular','Uma foto sua durante a noite apareceu em uma página esportiva. Um jornalista pede uma reação.','[{"key":"normal","label":"“Era meu tempo livre. Estou totalmente comprometido com o clube.”","result":"Você tratou o assunto como parte normal da vida fora do futebol.","effects":{"media":2,"fans":1,"coach":-1,"board":-1,"image":1}},{"key":"apologize","label":"“Talvez não tenha sido o melhor momento. Vou cuidar melhor disso.”","result":"A postura reduziu a polêmica, mas reforçou que havia algo a explicar.","effects":{"media":-1,"fans":1,"coach":3,"board":3,"image":-1,"discipline":3}},{"key":"attack_press","label":"“Estão procurando problema onde não existe.”","result":"A resposta aumentou a temperatura da história e dividiu a torcida.","effects":{"media":-6,"fans":3,"coach":-2,"board":-3,"image":3,"pressure":5,"ego":4}}]'),
('sponsor_quote','Patrocinador','Uma frase para a campanha','No fim do evento, a equipe de comunicação pede uma frase curta para publicar nas redes.','[{"key":"club","label":"“Representar este clube é uma responsabilidade enorme.”","result":"A publicação reforçou sua ligação com o clube.","effects":{"fans":4,"board":4,"image":3,"media":1,"locker":1}},{"key":"personal","label":"“É só o começo. Quero que todos lembrem do meu nome.”","result":"A frase chamou atenção e fortaleceu sua marca pessoal.","effects":{"image":7,"media":4,"fans":1,"locker":-2,"board":-1,"pressure":4,"ambition":3,"ego":3}},{"key":"simple","label":"“Feliz pela oportunidade. Obrigado a todos que acompanham.”","result":"A mensagem foi segura e evitou qualquer ruído.","effects":{"image":2,"fans":2,"board":2,"media":0}}]')
ON CONFLICT (event_key) DO UPDATE SET source=EXCLUDED.source,title=EXCLUDED.title,body=EXCLUDED.body,choices=EXCLUDED.choices;

CREATE OR REPLACE FUNCTION private.career_clamp(p_value INT) RETURNS INT LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT GREATEST(0,LEAST(100,COALESCE(p_value,0))); $$;
CREATE OR REPLACE FUNCTION private.career_relation_label(p_value INT) RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT CASE WHEN p_value>=82 THEN 'Excelente' WHEN p_value>=65 THEN 'Boa' WHEN p_value>=45 THEN 'Estável' WHEN p_value>=28 THEN 'Delicada' ELSE 'Tensa' END; $$;
CREATE OR REPLACE FUNCTION private.career_risk_label(p_energy INT,p_fatigue INT,p_injury_days INT) RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT CASE WHEN p_injury_days>0 THEN 'Lesionado' WHEN p_energy<42 OR p_fatigue>=72 THEN 'Muito alto' WHEN p_energy<55 OR p_fatigue>=58 THEN 'Alto' WHEN p_energy<70 OR p_fatigue>=38 THEN 'Moderado' ELSE 'Baixo' END; $$;

CREATE OR REPLACE FUNCTION private.add_skill_progress(p_player_id UUID,p_skill_key TEXT,p_points NUMERIC) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_level INT;v_progress NUMERIC;v_total NUMERIC;v_gain INT;
BEGIN IF p_points<=0 THEN RETURN; END IF; SELECT level,progress INTO v_level,v_progress FROM public.player_skill_development WHERE player_id=p_player_id AND skill_key=p_skill_key FOR UPDATE; IF v_level IS NULL OR v_level>=99 THEN RETURN; END IF; v_total:=v_progress+p_points;v_gain:=FLOOR(v_total/100);v_level:=LEAST(99,v_level+v_gain);v_progress:=CASE WHEN v_level>=99 THEN 0 ELSE MOD(v_total,100) END;UPDATE public.player_skill_development SET level=v_level,progress=v_progress,updated_at=now() WHERE player_id=p_player_id AND skill_key=p_skill_key;END;$$;

CREATE OR REPLACE FUNCTION private.apply_career_effects(p_player_id UUID,p_effects JSONB) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_skills JSONB;v_pair RECORD;
BEGIN UPDATE public.player_career_state SET energy=private.career_clamp(energy+COALESCE((p_effects->>'energy')::INT,0)),fatigue=private.career_clamp(fatigue+COALESCE((p_effects->>'fatigue')::INT,0)),morale=private.career_clamp(morale+COALESCE((p_effects->>'morale')::INT,0)),trust=private.career_clamp(trust+COALESCE((p_effects->>'coach')::INT,0)),form=private.career_clamp(form+COALESCE((p_effects->>'form')::INT,0)),media_relation=private.career_clamp(media_relation+COALESCE((p_effects->>'media')::INT,0)),fan_relation=private.career_clamp(fan_relation+COALESCE((p_effects->>'fans')::INT,0)),locker_room_relation=private.career_clamp(locker_room_relation+COALESCE((p_effects->>'locker')::INT,0)),board_relation=private.career_clamp(board_relation+COALESCE((p_effects->>'board')::INT,0)),agent_relation=private.career_clamp(agent_relation+COALESCE((p_effects->>'agent')::INT,0)),public_image=private.career_clamp(public_image+COALESCE((p_effects->>'image')::INT,0)),personal_life=private.career_clamp(personal_life+COALESCE((p_effects->>'personal')::INT,0)),pressure=private.career_clamp(pressure+COALESCE((p_effects->>'pressure')::INT,0)),cash_balance=GREATEST(0,cash_balance+COALESCE((p_effects->>'cash')::INT,0)),personality=personality||jsonb_build_object('professionalism',private.career_clamp(COALESCE((personality->>'professionalism')::INT,50)+COALESCE((p_effects->>'professionalism')::INT,0)),'ambition',private.career_clamp(COALESCE((personality->>'ambition')::INT,50)+COALESCE((p_effects->>'ambition')::INT,0)),'leadership',private.career_clamp(COALESCE((personality->>'leadership')::INT,40)+COALESCE((p_effects->>'leadership')::INT,0)),'discipline',private.career_clamp(COALESCE((personality->>'discipline')::INT,50)+COALESCE((p_effects->>'discipline')::INT,0)),'sociability',private.career_clamp(COALESCE((personality->>'sociability')::INT,50)+COALESCE((p_effects->>'sociability')::INT,0)),'ego',private.career_clamp(COALESCE((personality->>'ego')::INT,45)+COALESCE((p_effects->>'ego')::INT,0))),updated_at=now() WHERE player_id=p_player_id;v_skills:=p_effects->'skills';IF v_skills IS NOT NULL AND jsonb_typeof(v_skills)='object' THEN FOR v_pair IN SELECT key,value FROM jsonb_each_text(v_skills) LOOP PERFORM private.add_skill_progress(p_player_id,v_pair.key,v_pair.value::NUMERIC);END LOOP;END IF;END;$$;

CREATE OR REPLACE FUNCTION private.spawn_career_event(p_player_id UUID,p_event_key TEXT) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_template RECORD;v_public_choices JSONB;v_id UUID;
BEGIN IF EXISTS(SELECT 1 FROM public.player_career_events WHERE player_id=p_player_id AND event_key=p_event_key AND status='pending') THEN SELECT id INTO v_id FROM public.player_career_events WHERE player_id=p_player_id AND event_key=p_event_key AND status='pending' ORDER BY created_at DESC LIMIT 1;RETURN v_id;END IF;SELECT * INTO v_template FROM private.career_event_templates WHERE event_key=p_event_key;IF v_template.event_key IS NULL THEN RETURN NULL;END IF;SELECT COALESCE(jsonb_agg(jsonb_build_object('key',e->>'key','label',e->>'label')),'[]'::jsonb) INTO v_public_choices FROM jsonb_array_elements(v_template.choices)e;INSERT INTO public.player_career_events(player_id,event_key,source,title,body,choices) VALUES(p_player_id,v_template.event_key,v_template.source,v_template.title,v_template.body,v_public_choices) RETURNING id INTO v_id;RETURN v_id;END;$$;

CREATE OR REPLACE FUNCTION private.ensure_career_initialized(p_player_id UUID) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_attrs JSONB;v_state RECORD;v_contract RECORD;v_start DATE;v_next_match DATE;v_dow INT;v_objective JSONB;
BEGIN SELECT * INTO v_contract FROM public.player_contracts WHERE player_id=p_player_id AND status='active' ORDER BY signed_at DESC LIMIT 1;IF v_contract.id IS NULL THEN RAISE EXCEPTION 'O jogador ainda não possui contrato ativo.';END IF;SELECT * INTO v_state FROM public.player_career_state WHERE player_id=p_player_id FOR UPDATE;IF v_state.player_id IS NULL THEN RAISE EXCEPTION 'Estado da carreira não encontrado.';END IF;v_start:=COALESCE(v_state.career_date,CURRENT_DATE);v_dow:=EXTRACT(DOW FROM v_start)::INT;v_next_match:=v_start+CASE WHEN v_dow=6 THEN 7 ELSE(6-v_dow)END;IF v_state.hierarchy IN('Titular','Estrela') THEN v_objective:=jsonb_build_object('title','Chegar pronto para a estreia','description','Gerencie carga, recuperação e ambiente para chegar ao sábado em boas condições.','target','readiness');ELSIF v_state.hierarchy='Rotação' THEN v_objective:=jsonb_build_object('title','Ganhar confiança na semana','description','Mostre presença nos treinos coletivos sem deixar a estafa sair do controle.','target','trust');ELSE v_objective:=jsonb_build_object('title','Mostrar que merece espaço','description','Aproveite os treinos do clube e desenvolva uma especialidade antes do próximo jogo.','target','development');END IF;UPDATE public.player_career_state SET career_date=v_start,next_match_date=COALESCE(next_match_date,v_next_match),weekly_objective=CASE WHEN weekly_objective='{}'::jsonb THEN v_objective ELSE weekly_objective END,cash_balance=CASE WHEN financial_credit_applied=false THEN cash_balance+pending_initial_balance ELSE cash_balance END,financial_credit_applied=true,pending_initial_balance=CASE WHEN financial_credit_applied=false THEN 0 ELSE pending_initial_balance END,last_salary_date=COALESCE(last_salary_date,v_start),updated_at=now() WHERE player_id=p_player_id;SELECT atributos INTO v_attrs FROM public.jogadores WHERE id=p_player_id;
INSERT INTO public.player_skill_development(player_id,skill_key,label,category,parent_attribute,level,progress) VALUES
(p_player_id,'dribbling','Drible','Técnica','Velocidade',GREATEST(1,LEAST(99,ROUND(((v_attrs->>'Velocidade')::INT+(v_attrs->>'Passe')::INT)/2.0)::INT)),20),(p_player_id,'free_kicks','Faltas','Técnica','Passe',GREATEST(1,LEAST(99,ROUND(((v_attrs->>'Passe')::INT+(v_attrs->>'Visão de jogo')::INT)/2.0)::INT-8)),12),(p_player_id,'penalties','Pênaltis','Técnica','Finalização',GREATEST(1,LEAST(99,(v_attrs->>'Finalização')::INT-2)),15),(p_player_id,'short_pass','Passe curto','Técnica','Passe',GREATEST(1,LEAST(99,(v_attrs->>'Passe')::INT)),25),(p_player_id,'long_pass','Passe longo','Técnica','Passe',GREATEST(1,LEAST(99,ROUND(((v_attrs->>'Passe')::INT+(v_attrs->>'Visão de jogo')::INT)/2.0)::INT-4)),10),(p_player_id,'crossing','Cruzamento','Técnica','Passe',GREATEST(1,LEAST(99,(v_attrs->>'Passe')::INT-5)),10),(p_player_id,'positioning','Posicionamento','Tática','Visão de jogo',GREATEST(1,LEAST(99,(v_attrs->>'Visão de jogo')::INT)),20),(p_player_id,'tactical_awareness','Leitura tática','Tática','Visão de jogo',GREATEST(1,LEAST(99,ROUND(((v_attrs->>'Visão de jogo')::INT+(v_attrs->>'Marcação')::INT)/2.0)::INT)),10),(p_player_id,'sprint','Sprint','Físico','Velocidade',GREATEST(1,LEAST(99,(v_attrs->>'Velocidade')::INT)),20),(p_player_id,'stamina','Resistência','Físico','Físico',GREATEST(1,LEAST(99,(v_attrs->>'Físico')::INT)),20),(p_player_id,'strength','Força','Físico','Físico',GREATEST(1,LEAST(99,(v_attrs->>'Físico')::INT)),15),(p_player_id,'heading','Cabeceio','Físico','Físico',GREATEST(1,LEAST(99,ROUND(((v_attrs->>'Físico')::INT+(v_attrs->>'Finalização')::INT)/2.0)::INT-4)),8),(p_player_id,'finishing_touch','Conclusão','Técnica','Finalização',GREATEST(1,LEAST(99,(v_attrs->>'Finalização')::INT)),25),(p_player_id,'marking','Marcação','Defesa','Marcação',GREATEST(1,LEAST(99,(v_attrs->>'Marcação')::INT)),20) ON CONFLICT(player_id,skill_key)DO NOTHING;IF NOT EXISTS(SELECT 1 FROM public.player_career_events WHERE player_id=p_player_id)THEN PERFORM private.spawn_career_event(p_player_id,'arrival_dressing_room');END IF;END;$$;

CREATE OR REPLACE FUNCTION private.team_session_for_period(p_date DATE,p_period SMALLINT,p_coach_profile TEXT) RETURNS JSONB LANGUAGE plpgsql IMMUTABLE SET search_path='' AS $$
DECLARE v_dow INT:=EXTRACT(DOW FROM p_date)::INT;v_load TEXT;
BEGIN IF p_period<>0 THEN RETURN NULL;END IF;v_load:=CASE WHEN p_coach_profile='Rígido' THEN 'Alta' WHEN p_coach_profile='Amigável' THEN 'Moderada' ELSE 'Moderada' END;RETURN CASE v_dow WHEN 1 THEN jsonb_build_object('key','team_physical','title','Treino coletivo · Físico e intensidade','description','Trabalho do grupo com foco em ritmo, duelos e carga física.','load',v_load,'mandatory',true) WHEN 2 THEN jsonb_build_object('key','team_tactical','title','Treino coletivo · Organização tática','description','Movimentos coordenados, posicionamento e comportamento sem a bola.','load','Moderada','mandatory',true) WHEN 4 THEN jsonb_build_object('key','team_collective','title','Treino coletivo · Situações de jogo','description','Trabalho com o elenco em transições e construção de jogadas.','load',v_load,'mandatory',true) WHEN 5 THEN jsonb_build_object('key','team_setpieces','title','Treino coletivo · Bola parada','description','Rotinas ofensivas e defensivas antes do próximo compromisso.','load','Baixa','mandatory',true) WHEN 6 THEN jsonb_build_object('key','team_activation','title','Ativação pré-jogo','description','Sessão curta para manter o corpo pronto sem aumentar demais a carga.','load','Baixa','mandatory',true) ELSE NULL END;END;$$;

CREATE OR REPLACE FUNCTION private.advance_career_clock(p_player_id UUID) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_state RECORD;v_new_date DATE;v_new_period SMALLINT;v_contract RECORD;
BEGIN SELECT * INTO v_state FROM public.player_career_state WHERE player_id=p_player_id FOR UPDATE;v_new_date:=v_state.career_date;v_new_period:=v_state.day_period+1;IF v_new_period>2 THEN v_new_period:=0;v_new_date:=v_state.career_date+1;UPDATE public.player_career_state SET energy=private.career_clamp(energy+12),fatigue=private.career_clamp(fatigue-4),pressure=private.career_clamp(pressure-2),injury_days=GREATEST(0,injury_days-1),injury_status=CASE WHEN injury_days-1<=0 THEN 'healthy' ELSE injury_status END,injury_label=CASE WHEN injury_days-1<=0 THEN NULL ELSE injury_label END WHERE player_id=p_player_id;SELECT * INTO v_contract FROM public.player_contracts WHERE player_id=p_player_id AND status='active' ORDER BY signed_at DESC LIMIT 1;IF v_state.last_salary_date IS NOT NULL AND v_new_date>=v_state.last_salary_date+30 THEN UPDATE public.player_career_state SET cash_balance=cash_balance+COALESCE(v_contract.monthly_wage,0),last_salary_date=v_new_date WHERE player_id=p_player_id;INSERT INTO public.player_messages(player_id,club_id,message_type,subject,body,metadata)VALUES(p_player_id,v_contract.club_id,'career','Salário recebido','O pagamento mensal do seu contrato foi depositado na sua conta.',jsonb_build_object('kind','salary','amount',COALESCE(v_contract.monthly_wage,0)));END IF;END IF;UPDATE public.player_career_state SET career_date=v_new_date,day_period=v_new_period,updated_at=now() WHERE player_id=p_player_id;END;$$;

CREATE OR REPLACE FUNCTION public.get_career_hub() RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_user UUID:=auth.uid();v_player RECORD;v_state RECORD;v_contract RECORD;v_club RECORD;v_coach RECORD;v_session JSONB;v_readiness INT;v_actions JSONB;v_skills JSONB;v_event JSONB;v_recent JSONB;v_week JSONB;v_unread INT;v_match_locked BOOLEAN;
BEGIN IF v_user IS NULL THEN RAISE EXCEPTION 'Não autenticado.';END IF;SELECT * INTO v_player FROM public.jogadores WHERE user_id=v_user;IF v_player.id IS NULL THEN RAISE EXCEPTION 'Jogador não encontrado.';END IF;PERFORM private.ensure_career_initialized(v_player.id);SELECT * INTO v_state FROM public.player_career_state WHERE player_id=v_player.id;SELECT * INTO v_contract FROM public.player_contracts WHERE player_id=v_player.id AND status='active' ORDER BY signed_at DESC LIMIT 1;SELECT * INTO v_club FROM public.base_clubs WHERE id=v_contract.club_id;SELECT * INTO v_coach FROM public.base_coaches WHERE id=v_club.coach_id;v_session:=private.team_session_for_period(v_state.career_date,v_state.day_period,v_coach.profile);v_match_locked:=v_state.career_date>=v_state.next_match_date AND v_state.day_period>=1;v_readiness:=private.career_clamp(ROUND((v_state.energy*.45)+((100-v_state.fatigue)*.28)+(v_state.morale*.14)+(v_state.form*.13)-CASE WHEN v_state.injury_days>0 THEN 25 ELSE 0 END)::INT);
SELECT COALESCE(jsonb_agg(jsonb_build_object('key',activity_key,'category',category,'title',title,'description',description,'icon',icon,'load',load_label,'supports_intensity',supports_intensity,'supports_duration',supports_duration,'base_duration',base_duration,'disabled_reason',CASE WHEN v_state.injury_days>0 AND activity_key IN('sprint','strength','dribble_session','finishing')THEN 'Você está em recuperação e este trabalho físico não está liberado.' WHEN cash_delta<0 AND v_state.cash_balance<ABS(cash_delta)THEN 'Saldo insuficiente para esta atividade.' ELSE NULL END)ORDER BY category,title),'[]'::jsonb)INTO v_actions FROM private.career_activity_catalog;SELECT COALESCE(jsonb_agg(jsonb_build_object('key',skill_key,'label',label,'category',category,'parent_attribute',parent_attribute,'level',level,'progress',ROUND(progress,0))ORDER BY category,label),'[]'::jsonb)INTO v_skills FROM public.player_skill_development WHERE player_id=v_player.id;SELECT to_jsonb(e)INTO v_event FROM(SELECT id,event_key,source,title,body,choices,status,created_at FROM public.player_career_events WHERE player_id=v_player.id AND status='pending' ORDER BY created_at ASC LIMIT 1)e;SELECT COALESCE(jsonb_agg(to_jsonb(a)ORDER BY a.created_at DESC),'[]'::jsonb)INTO v_recent FROM(SELECT id,career_date,day_period,activity_key,category,title,intensity,duration_minutes,result_summary,created_at FROM public.player_career_actions WHERE player_id=v_player.id ORDER BY created_at DESC LIMIT 6)a;SELECT COALESCE(jsonb_agg(jsonb_build_object('date',d::date,'label',to_char(d,'DD/MM'),'dow',EXTRACT(DOW FROM d)::INT,'morning',private.team_session_for_period(d::date,0::smallint,v_coach.profile),'is_match_day',(d::date=v_state.next_match_date))ORDER BY d),'[]'::jsonb)INTO v_week FROM generate_series(v_state.career_date::timestamp,(v_state.career_date+6)::timestamp,interval '1 day')d;SELECT COUNT(*)INTO v_unread FROM public.player_messages WHERE player_id=v_player.id AND is_read=false;
RETURN jsonb_build_object('player',jsonb_build_object('id',v_player.id,'name',v_player.nome,'nickname',v_player.apelido,'avatar',v_player.avatar,'age',v_player.idade,'position',v_player.posicao,'archetype',v_player.arquetipo,'attributes',v_player.atributos),'club',jsonb_build_object('id',v_club.id,'name',v_club.name,'shield_url',v_club.shield_url,'formation',v_club.formation,'play_style',v_club.play_style),'coach',jsonb_build_object('id',v_coach.id,'name',v_coach.name,'profile',v_coach.profile),'contract',jsonb_build_object('monthly_wage',v_contract.monthly_wage,'squad_role',v_contract.squad_role,'duration_seasons',v_contract.duration_seasons),'state',jsonb_build_object('date',v_state.career_date,'period',v_state.day_period,'next_match_date',v_state.next_match_date,'energy',v_state.energy,'fatigue',v_state.fatigue,'readiness',v_readiness,'injury_risk',private.career_risk_label(v_state.energy,v_state.fatigue,v_state.injury_days),'injury_status',v_state.injury_status,'injury_label',v_state.injury_label,'injury_days',v_state.injury_days,'morale',private.career_relation_label(v_state.morale),'trust',private.career_relation_label(v_state.trust),'form',private.career_relation_label(v_state.form),'pressure',CASE WHEN v_state.pressure>=75 THEN 'Muito alta' WHEN v_state.pressure>=55 THEN 'Alta' WHEN v_state.pressure>=35 THEN 'Moderada' ELSE 'Baixa' END,'cash',v_state.cash_balance,'hierarchy',v_state.hierarchy,'weekly_objective',v_state.weekly_objective,'environment',jsonb_build_object('coach',private.career_relation_label(v_state.trust),'locker_room',private.career_relation_label(v_state.locker_room_relation),'fans',private.career_relation_label(v_state.fan_relation),'media',private.career_relation_label(v_state.media_relation),'board',private.career_relation_label(v_state.board_relation),'agent',private.career_relation_label(v_state.agent_relation),'public_image',private.career_relation_label(v_state.public_image),'personal_life',private.career_relation_label(v_state.personal_life))),'current_session',v_session,'match_locked',v_match_locked,'activities',v_actions,'skills',v_skills,'pending_event',v_event,'recent_actions',v_recent,'week',v_week,'unread_messages',v_unread);END;$$;

CREATE OR REPLACE FUNCTION public.perform_career_activity(p_activity_key TEXT,p_intensity TEXT DEFAULT 'normal',p_duration INT DEFAULT 60) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_user UUID:=auth.uid();v_player RECORD;v_state RECORD;v_contract RECORD;v_club RECORD;v_coach RECORD;v_session JSONB;v_activity RECORD;v_duration_mult NUMERIC:=1;v_gain_mult NUMERIC:=1;v_cost_mult NUMERIC:=1;v_repeat_count INT:=0;v_repeat_mult NUMERIC:=1;v_skill JSONB:='{}'::jsonb;v_pair RECORD;v_risk NUMERIC:=0;v_injured BOOLEAN:=false;v_title TEXT;v_summary TEXT;v_category TEXT;v_event_id UUID;v_roll NUMERIC;v_effects JSONB;
BEGIN IF v_user IS NULL THEN RAISE EXCEPTION 'Não autenticado.';END IF;SELECT * INTO v_player FROM public.jogadores WHERE user_id=v_user;IF v_player.id IS NULL THEN RAISE EXCEPTION 'Jogador não encontrado.';END IF;PERFORM private.ensure_career_initialized(v_player.id);SELECT * INTO v_state FROM public.player_career_state WHERE player_id=v_player.id FOR UPDATE;SELECT * INTO v_contract FROM public.player_contracts WHERE player_id=v_player.id AND status='active' ORDER BY signed_at DESC LIMIT 1;SELECT * INTO v_club FROM public.base_clubs WHERE id=v_contract.club_id;SELECT * INTO v_coach FROM public.base_coaches WHERE id=v_club.coach_id;IF v_state.career_date>=v_state.next_match_date AND v_state.day_period>=1 THEN RAISE EXCEPTION 'Você chegou ao horário do jogo. A mecânica de partida ainda será definida.';END IF;v_session:=private.team_session_for_period(v_state.career_date,v_state.day_period,v_coach.profile);
IF v_session IS NOT NULL THEN IF p_activity_key NOT IN('team_training_light','team_training_normal','team_training_intense','team_training_skip')THEN RAISE EXCEPTION 'Há um treino coletivo agendado neste período. Escolha como participar.';END IF;v_title:=v_session->>'title';v_category:='team_training';IF p_activity_key='team_training_light' THEN v_effects:='{"energy":-7,"fatigue":2,"morale":0,"coach":1,"locker":1,"pressure":-1,"skills":{"tactical_awareness":4}}';v_summary:='Você participou do treino do time com carga reduzida.';v_risk:=1;ELSIF p_activity_key='team_training_normal' THEN v_effects:='{"energy":-12,"fatigue":6,"morale":1,"coach":4,"locker":2,"pressure":-1,"skills":{"tactical_awareness":8,"positioning":4}}';v_summary:='Você cumpriu a sessão coletiva no ritmo pedido pelo treinador.';v_risk:=3;ELSIF p_activity_key='team_training_intense' THEN v_effects:='{"energy":-18,"fatigue":10,"morale":1,"coach":5,"locker":2,"pressure":1,"skills":{"tactical_awareness":11,"positioning":6,"stamina":4}}';v_summary:='Você foi além da carga normal e chamou atenção pela intensidade.';v_risk:=10;ELSE v_effects:='{"energy":10,"fatigue":-5,"morale":2,"coach":-10,"locker":-3,"board":-1,"pressure":2,"discipline":-4}';v_summary:='Você não participou do treino coletivo e priorizou a recuperação.';v_risk:=0;INSERT INTO public.player_messages(player_id,club_id,message_type,subject,body,metadata)VALUES(v_player.id,v_club.id,'career','Ausência no treino coletivo',v_coach.name||' registrou sua ausência na atividade do grupo. A decisão pode pesar na forma como o treinador enxerga seu comprometimento.',jsonb_build_object('kind','coach_reaction','activity','team_training_skip'));END IF;
ELSE SELECT * INTO v_activity FROM private.career_activity_catalog WHERE activity_key=p_activity_key;IF v_activity.activity_key IS NULL THEN RAISE EXCEPTION 'Atividade inválida.';END IF;IF v_state.injury_days>0 AND p_activity_key IN('sprint','strength','dribble_session','finishing')THEN RAISE EXCEPTION 'A equipe médica não liberou esta atividade durante sua recuperação.';END IF;IF v_activity.cash_delta<0 AND v_state.cash_balance<ABS(v_activity.cash_delta)THEN RAISE EXCEPTION 'Saldo insuficiente para esta atividade.';END IF;IF p_intensity NOT IN('light','normal','intense')THEN RAISE EXCEPTION 'Intensidade inválida.';END IF;IF p_duration NOT IN(30,60,90)THEN RAISE EXCEPTION 'Duração inválida.';END IF;IF NOT v_activity.supports_intensity THEN p_intensity:='normal';END IF;IF NOT v_activity.supports_duration THEN p_duration:=v_activity.base_duration;END IF;v_duration_mult:=CASE p_duration WHEN 30 THEN .65 WHEN 90 THEN 1.35 ELSE 1 END;v_gain_mult:=CASE p_intensity WHEN 'light' THEN .72 WHEN 'intense' THEN 1.35 ELSE 1 END;v_cost_mult:=CASE p_intensity WHEN 'light' THEN .62 WHEN 'intense' THEN 1.55 ELSE 1 END;SELECT COUNT(*)INTO v_repeat_count FROM public.player_career_actions WHERE player_id=v_player.id AND activity_key=p_activity_key AND career_date>=v_state.career_date-2;v_repeat_mult:=GREATEST(.45,1-(v_repeat_count*.18));FOR v_pair IN SELECT key,value FROM jsonb_each_text(v_activity.skill_effects)LOOP v_skill:=v_skill||jsonb_build_object(v_pair.key,ROUND(v_pair.value::NUMERIC*v_duration_mult*v_gain_mult*v_repeat_mult,2));END LOOP;v_effects:=jsonb_build_object('energy',ROUND(CASE WHEN v_activity.energy_delta<0 THEN v_activity.energy_delta*v_duration_mult*v_cost_mult ELSE v_activity.energy_delta END)::INT,'fatigue',ROUND(CASE WHEN v_activity.fatigue_delta>0 THEN v_activity.fatigue_delta*v_duration_mult*v_cost_mult ELSE v_activity.fatigue_delta END)::INT,'morale',v_activity.morale_delta,'coach',v_activity.trust_delta,'form',v_activity.form_delta,'media',v_activity.media_delta,'fans',v_activity.fan_delta,'locker',v_activity.locker_delta,'board',v_activity.board_delta,'agent',v_activity.agent_delta,'image',v_activity.image_delta,'personal',v_activity.personal_delta,'pressure',v_activity.pressure_delta,'cash',v_activity.cash_delta,'skills',v_skill);v_title:=v_activity.title;v_category:=v_activity.category;v_summary:=v_activity.result_summary;v_risk:=v_activity.base_injury_risk+GREATEST(0,50-v_state.energy)*.45+GREATEST(0,v_state.fatigue-50)*.45+CASE WHEN p_intensity='intense'THEN 10 ELSE 0 END+CASE WHEN p_duration=90 THEN 4 ELSE 0 END;IF v_activity.event_key IS NOT NULL THEN IF v_activity.event_key='night_out_spotted' THEN v_roll:=random();IF v_roll<.34 THEN v_event_id:=private.spawn_career_event(v_player.id,v_activity.event_key);END IF;ELSE v_event_id:=private.spawn_career_event(v_player.id,v_activity.event_key);END IF;END IF;END IF;
PERFORM private.apply_career_effects(v_player.id,v_effects);SELECT * INTO v_state FROM public.player_career_state WHERE player_id=v_player.id FOR UPDATE;IF v_state.injury_days=0 AND v_risk>0 AND random()*100<LEAST(55,v_risk)THEN v_injured:=true;UPDATE public.player_career_state SET injury_status='minor',injury_label='Sobrecarga muscular',injury_days=2+FLOOR(random()*4)::INT,fatigue=private.career_clamp(fatigue+6),energy=private.career_clamp(energy-5),updated_at=now()WHERE player_id=v_player.id;v_summary:=v_summary||' No fim da atividade, você sentiu uma sobrecarga e foi encaminhado para avaliação.';INSERT INTO public.player_messages(player_id,club_id,message_type,subject,body,metadata)VALUES(v_player.id,v_club.id,'career','Departamento médico','Você apresentou sinais de sobrecarga muscular. A equipe médica recomenda reduzir a carga até a liberação.',jsonb_build_object('kind','medical','status','minor'));END IF;INSERT INTO public.player_career_actions(player_id,career_date,day_period,activity_key,category,title,intensity,duration_minutes,result_summary,hidden_effects)VALUES(v_player.id,v_state.career_date,v_state.day_period,p_activity_key,v_category,v_title,CASE WHEN v_session IS NULL THEN p_intensity ELSE replace(p_activity_key,'team_training_','')END,CASE WHEN v_session IS NULL THEN p_duration ELSE NULL END,v_summary,v_effects);PERFORM private.advance_career_clock(v_player.id);RETURN jsonb_build_object('success',true,'summary',v_summary,'event_created',v_event_id IS NOT NULL,'injured',v_injured);END;$$;

CREATE OR REPLACE FUNCTION public.advance_career_period() RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_user UUID:=auth.uid();v_player RECORD;v_state RECORD;v_contract RECORD;v_club RECORD;v_coach RECORD;v_session JSONB;
BEGIN IF v_user IS NULL THEN RAISE EXCEPTION 'Não autenticado.';END IF;SELECT * INTO v_player FROM public.jogadores WHERE user_id=v_user;IF v_player.id IS NULL THEN RAISE EXCEPTION 'Jogador não encontrado.';END IF;PERFORM private.ensure_career_initialized(v_player.id);SELECT * INTO v_state FROM public.player_career_state WHERE player_id=v_player.id FOR UPDATE;SELECT * INTO v_contract FROM public.player_contracts WHERE player_id=v_player.id AND status='active' ORDER BY signed_at DESC LIMIT 1;SELECT * INTO v_club FROM public.base_clubs WHERE id=v_contract.club_id;SELECT * INTO v_coach FROM public.base_coaches WHERE id=v_club.coach_id;IF v_state.career_date>=v_state.next_match_date AND v_state.day_period>=1 THEN RETURN jsonb_build_object('success',false,'match_pending',true,'message','Você chegou ao horário do jogo. A partida fica parada aqui até definirmos a mecânica.');END IF;v_session:=private.team_session_for_period(v_state.career_date,v_state.day_period,v_coach.profile);IF v_session IS NOT NULL THEN RAISE EXCEPTION 'Há um treino coletivo agendado. Escolha como participar antes de avançar.';END IF;PERFORM private.apply_career_effects(v_player.id,'{"energy":4,"fatigue":-2,"pressure":-1}');INSERT INTO public.player_career_actions(player_id,career_date,day_period,activity_key,category,title,result_summary,hidden_effects)VALUES(v_player.id,v_state.career_date,v_state.day_period,'free_period','recovery','Período livre','Você deixou o período passar sem marcar nenhuma atividade.','{"energy":4,"fatigue":-2,"pressure":-1}');PERFORM private.advance_career_clock(v_player.id);RETURN jsonb_build_object('success',true,'message','Período avançado.');END;$$;

CREATE OR REPLACE FUNCTION public.resolve_career_event(p_event_id UUID,p_choice_key TEXT) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE v_user UUID:=auth.uid();v_player RECORD;v_event RECORD;v_template RECORD;v_choice JSONB;v_effects JSONB;v_result TEXT;
BEGIN IF v_user IS NULL THEN RAISE EXCEPTION 'Não autenticado.';END IF;SELECT * INTO v_player FROM public.jogadores WHERE user_id=v_user;IF v_player.id IS NULL THEN RAISE EXCEPTION 'Jogador não encontrado.';END IF;SELECT * INTO v_event FROM public.player_career_events WHERE id=p_event_id AND player_id=v_player.id AND status='pending' FOR UPDATE;IF v_event.id IS NULL THEN RAISE EXCEPTION 'Decisão não encontrada ou já resolvida.';END IF;SELECT * INTO v_template FROM private.career_event_templates WHERE event_key=v_event.event_key;SELECT e INTO v_choice FROM jsonb_array_elements(v_template.choices)e WHERE e->>'key'=p_choice_key LIMIT 1;IF v_choice IS NULL THEN RAISE EXCEPTION 'Opção inválida.';END IF;v_effects:=COALESCE(v_choice->'effects','{}'::jsonb);v_result:=COALESCE(v_choice->>'result','Sua decisão foi registrada.');PERFORM private.apply_career_effects(v_player.id,v_effects);UPDATE public.player_career_events SET status='resolved',chosen_key=p_choice_key,result_text=v_result,resolved_at=now()WHERE id=p_event_id;RETURN jsonb_build_object('success',true,'result',v_result);END;$$;

REVOKE EXECUTE ON FUNCTION public.get_career_hub() FROM PUBLIC,anon;
REVOKE EXECUTE ON FUNCTION public.perform_career_activity(TEXT,TEXT,INT) FROM PUBLIC,anon;
REVOKE EXECUTE ON FUNCTION public.advance_career_period() FROM PUBLIC,anon;
REVOKE EXECUTE ON FUNCTION public.resolve_career_event(UUID,TEXT) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_career_hub() TO authenticated;
GRANT EXECUTE ON FUNCTION public.perform_career_activity(TEXT,TEXT,INT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.advance_career_period() TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_career_event(UUID,TEXT) TO authenticated;
